### ISSUE TITLE
ES6 code in assets/javascripts is not transpiling

### ISSUE THREAD

**Issue by seanaery** [projectblacklight/arclight#1010]
In the ArcLight demo, and in a freshly created ArcLight app, none of the ES6 syntax present in the `assets/javascripts` files in Blacklight nor in ArcLight is getting transpiled into ES5. This renders the UI broken/unusable in IE11 (reported in https://github.com/projectblacklight/arclight/issues/995 ).

Viewing the compiled `application.js`, it's minified, but not transpiled, so there are several arrow functions, backtick characters, and other ES6-isms, so in an older browser like IE11, these are interpreted as `INVALID CHARACTER` etc., and the subsequent code in the script is ignored.

It's unclear from existing documentation what steps an implementer must take to add transpiling to the pipeline.

Example ES6 in Blacklight scripts:
https://github.com/projectblacklight/blacklight/blob/master/app/javascript/blacklight/button_focus.js#L4
https://github.com/projectblacklight/blacklight/blob/master/app/assets/javascripts/blacklight/blacklight.js#L466-L467

**Comment by seanaery** [comment]
I noticed this exact problem was reported as a Blacklight issue earlier this year: https://github.com/projectblacklight/blacklight/issues/2252

**Comment by jcoyne** [comment]
We are not going to fix this. IE11 is no longer supported.
