### ISSUE TITLE
View more/less truncator for long abstract or scopecontent doesn't work in Firefox

### ISSUE THREAD

**Issue by seanaery** [projectblacklight/arclight#1027]
Example (click `view more`) under the first component's description; note the content from `document.abstract_or_scope` does not expand:
https://arclight-demo.projectblacklight.org/catalog/rushbenjaminandjulia (Contents Tab)

It behaves the same in search results, e.g., the collection headers:
https://arclight-demo.projectblacklight.org/catalog?f%5Brepository_sim%5D%5B%5D=David+M.+Rubenstein+Rare+Book+and+Manuscript+Library&group=true&q=&search_field=all_fields&view=list

Observed in:
- ArcLight 0.4.0
- Firefox 85.0.2
- Mac OS 10.15.2

It appears to be working fine in Chrome 88.0.x & Safari 13.0.4.

<img width="766" alt="Screen Shot 2021-02-19 at 4 16 15 PM" src="https://user-images.githubusercontent.com/3933756/108562424-d148bf80-72cd-11eb-9bd6-f985c2529c29.png">

**Comment by seanaery** [comment]
@tpendragon I saw that Princeton's stakeholders have spotted this bug as well in PULFAlight:
https://github.com/pulibrary/pulfalight/issues/561

Hopefully we'll be able to get it addressed in core.

**Comment by tpendragon** [comment]
@seanaery Thanks for the ping! That's good to hear, that bug's not prioritized for our release, so it's exciting it might be cleared up by the time we get to it.

**Comment by crugas** [comment]
Hi all, the University of Georgia is starting to implement ArcLight and we've also noted this problem. Is there any timeline for when this will get resolved?
