### ISSUE TITLE
Upstream Blacklight Change: _facet_group.html.erb breaks Collections page

### ISSUE THREAD

**Issue by dl-maura** [projectblacklight/arclight#1037]
I attempted to build and run from arc light template, and the Collections page is throwing errors due to what I believe is a change in Blacklight. To recreate, if you build a new app using the template, bring everything up in development mode, and click the Collections button. Rather than the Collections page, you will get a stack trace that seems to originate in the _facet_group.html.erb from Blacklight (I can post a screenshot in slack if that is useful, I don't think Github allows).

**Comment by tpendragon** [comment]
@dl-maura I think this got fixed, but I had to update Blacklight to 7.24.0.

**Comment by seanaery** [comment]
Resolving this issue as part of a review of `arclight 1.0.x`. This does not appear to be happening in an app generated via arclight v1, which currently specifies Blacklight 8+
