### ISSUE TITLE
Remove jQuery dependency

### ISSUE THREAD

**Issue by jcoyne** [projectblacklight/arclight#1050]
This will involve rewriting some of the javascript in this repo to not use jquery.

- [x] https://github.com/projectblacklight/arclight/pull/1214
- [x] https://github.com/projectblacklight/arclight/issues/1091
- [x] https://github.com/projectblacklight/arclight/pull/1213
- [x] https://github.com/projectblacklight/arclight/pull/1216
- [x] https://github.com/projectblacklight/arclight/pull/1043

**Comment by marlo-longley** [comment]
Blocked by https://github.com/projectblacklight/arclight/issues/1096
We should write a few tests before removing/breaking things.
