### ISSUE TITLE
Replace responsiveTruncate with pure CSS

### ISSUE THREAD

**Issue by jcoyne** [projectblacklight/arclight#1091]
https://css-tricks.com/line-clampin/

**Comment by thatbudakguy** [comment]
last time i looked, all of the pure css solutions still required knowing the number of lines beforehand. it looks like we don't know that:
https://github.com/projectblacklight/arclight/blob/809c34b30505145b5c12260ee0e3e1f9290ae273/vendor/assets/javascripts/responsiveTruncator.js#L25

if there is (finally!) a good solution that avoids that problem, I'd love to learn it!

**Comment by marlo-longley** [comment]
Question after discussing with @thatbudakguy: can we set the number of lines in stone based on the best UI, and dictate that to  CSS line clamp?

**Comment by thatbudakguy** [comment]
also for reference: marlo implemented [a mixin to do this on DLME](https://github.com/sul-dlss/dlme/pull/1466) using the `-webkit-line-clamp` strategy, which works provided we know the desired number of lines to clamp to beforehand.

need to figure out how it interacts with the show/hide button, though.

**Comment by jcoyne** [comment]
@thatbudakguy we currently clamp everything here to 3 lines:
https://github.com/projectblacklight/arclight/blob/main/app/assets/javascripts/arclight/responsiveTruncator.js#L18

Is that what you were asking?

**Comment by jcoyne** [comment]
FWIW, I don't think you need the browser specific prefixes anymore, it's available everywhere: https://caniuse.com/?search=line-clamp

**Comment by thatbudakguy** [comment]
oh — yep, it is. if it's always 3, that makes it easy!
