### ISSUE TITLE
Add tests for the oembed viewer

### ISSUE THREAD

**Issue by thatbudakguy** [projectblacklight/arclight#1096]
some of the javascript mentioned in #1050 doesn't have tests. the oEmbed stuff, for example, can be removed entirely without causing any tests to fail. we probably want at least a basic feature test in place before refactoring.

- [ ] oembed_viewer.js
- [x] responsive_truncator.js (this one is tested by `/spec/features/scope_truncation_spec.rb`)
- [x] context_navigation.js?
- [x] collection_navigation.js?

**Comment by marlo-longley** [comment]
`context_navigation.js`: Might not be that hard to remove jQuery but maybe needs a refactor to use ViewComponents, Turbo.
`context_navigation.js` is tested in these files:
1. `collection_context_spec.rb`
2. `collection_page_spec.rb`
3. `component_page_spec.rb`
4. `many_component_ead_spec.rb`
5. `scope_truncation_spec.rb`

**Comment by thatbudakguy** [comment]
798949f7fa2b88336679c83d1b7d6950af47e502 refactored the viewer to use a stimulus controller, and it's working in NTA, so closing this since we got it done without tests 🤷🏻
