### ISSUE TITLE
Unable to materialize the gemfile in rails 7

### ISSUE THREAD

**Issue by jcoyne** [projectblacklight/arclight#1129]
https://github.com/projectblacklight/arclight/actions/runs/3222899254/jobs/5272432959#step:5:198

This means that importmap is not correctly installed

Also seen in https://github.com/projectblacklight/arclight/actions/runs/3230875218/jobs/5289804477#step:5:198 for (https://github.com/projectblacklight/arclight/pull/1147)

**Comment by marlo-longley** [comment]
Closing because of new version of bundler in use.
