### ISSUE TITLE
Restructure the component-level UI layout

### ISSUE THREAD

**Issue by ggeisler** [projectblacklight/arclight#1148]
Since the last community workcycle on ArcLight, several institutions -- [Duke](https://archives.lib.duke.edu/catalog/jwticonographic) and [University at Albany, SUNY](https://archives.albany.edu/description/catalog/ua801-004), for example -- implemented production versions that included a significant change to the UI layout used for display component-level information (as opposed to the search results and home/repositories pages). Other institutions considering implementing ArcLight in the near future have also indicated preferring this updated UI layout.

Below is a very general description of the overall layout change. I think the Stanford developers currently working on ArcLight know how to find the relevant code from Duke to use as a more specific guide, when applicable. I'll also create more specific tickets that describe updates to individual sections that require more description and/or deviate somewhat from Duke's example.

<img width="1023" alt="Screen Shot 2022-10-11 at 5 00 49 PM" src="https://user-images.githubusercontent.com/101482/195220020-0df78027-7b2e-44b8-8254-a16c24d85561.png">

- [ ] Change the component-level show page layout from a single-column to two-columns, where the sidebar column is 1/3rd of the page width, and the main content column is 2/3rds of the page width (i.e., a 4/8 column split) . This is different from the 3/9 column split used on the search results page but 1) we need the sidebar to be wider to accommodate a potentially deeply nested (and therefore indented) collection navigation tree, and 2) I don't think there's any UX problem with having two different sidebar/main content area proportions in these two contexts.

---

More specifically, this comparison shows where the major parts of the UI move from the current version of ArcLight to the recommended updated layout:

<img width="1715" alt="Screen Shot 2022-10-11 at 5 01 33 PM" src="https://user-images.githubusercontent.com/101482/195220072-74691503-30f4-485a-bddc-7ac32f4bab0a.png">

**A: Breadcrumb section** - Moves to the top of the main content area, separated from the component title and details by a bottom border. See #1176 for details.

**B: Collection info** - Moves to the top section of the sidebar column. See #1175 for details.

**C: Collection overview** - This tab and related collection metadata is currently only displayed when you are at the top, collection-level component page. The vertical tabs indicated by the right-side "C" in the current page move to the middle section of the sidebar column, with a section title of `Collection overview`.

**D: Collection metadata** - The metadata shown in the current Overview tab is shown in the main content area when any of the "Collection overview" tabs are selected in the middle section of the sidebar. So the vertical navigation in the updated "Collection overview" section works the same as it currently does, determining which section heading has focus and is scrolled to the top of the main content area.

**E: Collection contents** - The current "Contents" (when at the collection level) or "Collection context" (when at a level below collection) tab is moved to the bottom section of the sidebar, in a section with the heading `Collection contents`. See #1174 for details.

**F: Online content** - The current "Online content" tab changes to a new info box below the component title, with a redirect to a search results page. See #1168 for details.

**G: Access info** - The current "Access" tab shows the collection level access statement when at the collection level, and can show more specific access statements when at a lower level component. The collection level access info moves to the end of the collection metadata, and component-specific access info will be shown at the end of the component details in the main content area. See #1166 for details.

**Comment by jcoyne** [comment]
@ggeisler Can you provide a mockup for what happens when you press "Show only online content"?

**Comment by ggeisler** [comment]
@jcoyne As I mentioned in my ticket description, I plan to provide more specific tickets that address details of individual sections of the general UI update. This ticket was meant as a general guide to how the layout should change. I'll address all of your questions in subsequent tickets or comments here when I have time.

**Comment by ggeisler** [comment]
@jcoyne 

> How do we differentiate between bookmarking the collection and bookmarking the item in the new designs?

I don't think the new layout changes anything with bookmarking. The bookmark control is still available in all the same places it currently is:


<img width="1197" alt="Screen Shot 2022-10-12 at 5 01 37 PM" src="https://user-images.githubusercontent.com/101482/195469424-2b2047db-0987-4f16-a7be-4f780f97aba0.png">

---

<img width="1197" alt="Screen Shot 2022-10-12 at 5 02 40 PM" src="https://user-images.githubusercontent.com/101482/195469447-0d0a0c5e-0957-422a-8b50-77da1414541a.png">

---

Plus the same bookmark affordance when displaying search results, which can display both collections and components, as we do now.
