### ISSUE TITLE
Component view layout update: Collection contents

### ISSUE THREAD

**Issue by ggeisler** [projectblacklight/arclight#1174]
One of the UI updates noted in https://github.com/projectblacklight/arclight/issues/1148 involves the hierarchical tree for the collection inventory. Currently there is a tab called "Contents" (when at the collection level) or "Collection context" (when at a component level; callout "E" in the screenshots below) that holds this hierarchical tree:

<img width="1870" alt="Screen Shot 2022-10-13 at 2 25 04 PM" src="https://user-images.githubusercontent.com/101482/195713807-86a82209-6736-4df7-bfa1-302285b458b7.png">

These both get replaced by moving the hierarchical tree to the sidebar, under the "Collection contents" heading. The basic function of the tree remains: selecting the expand/collapse icon opens/closes parent levels of the tree, while selecting the title of a component in the tree results in 1) adding a background highlight (I used `#f5f5f5` in the mockup) to indicate it is selected, and 2) loading that component's show page in the main content area.

(Note that if the collection itself is displayed in the main content area, then one of the nav items in the "Collection overview" section should be highlighted. Opening or closing a parent level in the collection contents tree alone shouldn't trigger highlighting of that item; an item should only be highlighted in the tree if it is selected and its show page is displayed in the main content area. In other words, what is showing in the main content area determines which item is highlighted in either the "Collection overview" or the "Collection contents" section.)

For example, here we've used the expand icon to open Series 1 to see its child components, while the collection access info is still displayed in the main content area:

<img width="1201" alt="Screen Shot 2022-10-13 at 2 33 13 PM" src="https://user-images.githubusercontent.com/101482/195715224-bdcfca30-ba2a-4cda-9a00-798f7a5af341.png">

---

And now we've selected the "Series 1" title itself, which loads the Series 1 component in the main content area:

<img width="1012" alt="Screen Shot 2022-10-13 at 1 52 42 PM" src="https://user-images.githubusercontent.com/101482/195711679-9dfd9de5-8d5a-4786-bcb6-145add111643.png">

---

Here we've selected one of the child components of Series 1 in the tree, which loads its show page in the main content area: 

<img width="1011" alt="Screen Shot 2022-10-13 at 2 01 49 PM" src="https://user-images.githubusercontent.com/101482/195711880-e6db3cb6-9c17-450a-9339-ee70b2ef0fec.png">

---

In these mockups I have used a different icon from what's used in the hierarchical tree currently. I'd prefer we switch from the current expand/collapse icon to one similar to what's in the mockup, mostly because it's more compact and we want to save as much horizontal space as we can with the tree in the sidebar. Plus the current icons are a little weak, visually.

Expand icon: https://fontawesome.com/icons/square-plus?s=solid&f=classic
Collapse icon: https://fontawesome.com/icons/square-minus?s=solid&f=classic

Color: Bootstrap `secondary`
Size: about `1rem` or about `14px` by `19px` (width by height).

**Comment by seanaery** [comment]
I'm reminded looking at these (excellent) mockups that we have something probably unique to Duke around requesting that led us to place the **Request** button where we did. Long story short, we don't store any barcodes for requestable containers in ArchivesSpace or in our EAD files, so unfortunately the **Request** action for us is something that is taken on a **Collection**, no matter where you are in our UI (collection or component). I suspect that might not be true for most other implementers.

E.g., I'm aware of work at Princeton and at University of Georgia Libraries to implement Aeon request links/buttons alongside particular components or containers within component lists. Not sure if that will end up in scope for this current round of core revisions, but thought I'd call attention to it. As is, I think if you were to transplant ArcLight's current Request button into that location in the sidebar, when you're on a component view it becomes a component request, and it might be misleading there among the collection-level actions.

**Comment by crugas** [comment]
Thanks for the shout-out Sean! At UGA, we've developed an Aeon Requesting functionality in our demo version of ArcLight that works really well with requesting at the container level in a place that we hope is more direct for users. Attached is a few images of what we have so far, but we would appreciate this kind of requesting functionality to be a part of the core, or easily applicable to the core.

---

![sclfind_aeon_request_demo-001](https://user-images.githubusercontent.com/62658840/196540862-16365329-c549-4f0f-b6c4-e3ad0bcbbe3c.gif)
Here, users can request boxes in the Inventory "Contents" tab by drilling down to the item level and having a "Request {Container} Number" button follow them as they scroll down. Users can click on the button repeatedly or where ex. Box 1 is in multiple places in a collection, the popup box at the top deduplicates the requests before a user submits it to our Aeon page. This means less headaches for our folks to do cleanup work in Aeon and simplifies the experience for users - not seeing 1000s of Box 1s. Plus, users can request things from different collections and when they are ready, submit them all at once from the cart.

---

![Aeon_request_popup_box-demo-003](https://user-images.githubusercontent.com/62658840/196542489-c93a7c7c-ef9e-4803-bedb-5580926547a4.png)
The popup cart allows users to request containers from multiple collections across repositories and submit their request at once. Once submitted, the requests are cleared from the cart.

---

![Aeon_request_popup_box-demo-004](https://user-images.githubusercontent.com/62658840/196543469-3e128a56-ed2b-46bf-b749-d34720523e43.png)
This demonstrates that where items have the same containers appear multiple times but in a different order, it displays the request button every time a different container appears. If a user clicks on "Request Box 199" in those 2 places, the popup will deduplicate the requests so it appears only once in the cart and is submitted once through Aeon.

**Comment by ggeisler** [comment]
@seanaery Thanks for pointing out this issue with the Request button. I definitely overlooked the drawback to the location of the Request button when doing the mockups and I agree with you that the Duke approach might not be the most ideal for a generic ArcLight implementation. It is kind of unintuitive to have one thing that might not be collection-specific mixed in with the other collection-level information (though I like your approach with the Request button tooltip to clarify things for the user).

@crugas Thanks for the great illustrations and explanation of how UGA's implementation has dealt with the Request button issue. Your approach seems very intuitive and user friendly. I appreciate you taking the time to put that all together.

I do think we need to move the Request button. I'm a bit unsure of how we handle things at this stage, though, just because: 1) the Stanford team currently doing work on ArcLight has limited time left, and 2) as polished as the UGA solution is, I worry about it being too specific for a vanilla ArcLight implementation. I could definitely be wrong about that, and maybe one of the developers currently working on ArcLight could weigh in on whether the UGA approach seems appropriate and feasible for vanilla ArcLight, but I believe in the last ArcLight community workcycle we specifically avoided making any assumptions about the request process beyond the button itself, since institutions vary a lot in how they handle requests, whether they use Aeon or not, etc.

Based on your experience, @seanaery and @crugas, what do you think about this very simple first step in addressing the Request button issue: simply move the Request button to the component title area, next to the bookmark controls? That way it is fairly visible and more clearly associated with the current component. So for the collection itself:

<img width="1010" alt="Screen Shot 2022-10-31 at 3 05 03 PM" src="https://user-images.githubusercontent.com/101482/199121493-959fcce6-1d10-4216-b6a8-43f240136731.png">

---

A series component:

<img width="1010" alt="Screen Shot 2022-10-31 at 3 05 44 PM" src="https://user-images.githubusercontent.com/101482/199121546-662d4a56-bf67-465f-b581-fe599b37f984.png">

---

And a file-level component:

<img width="1010" alt="Screen Shot 2022-10-31 at 3 06 13 PM" src="https://user-images.githubusercontent.com/101482/199121580-c2cb318e-9095-4dc3-8f84-eb7f6ac13271.png">

---

There is a downside in taking more horizontal space away from the component title, but it's relatively small (~70px).

This doesn't address all the additional enhancements made in the UGA approach, but perhaps this could be a first step, and then a future chunk of work could be extending it with the work UGA did?

**Comment by seanaery** [comment]
@ggeisler That looks like a good move to me. My recollection matches yours about having very few assumptions baked into the requesting process given how widely divergent implementers' needs proved to be (even among Aeon users) during the last workcycle. I think the UGA work would be challenging to generalize and incorporate into core on a tight timeline, yet would be useful to keep bookmarked for future consideration.

**Comment by crugas** [comment]
I think this is a step in the right direction. I agree with @seanaery - since the dev time is limited and this is a local solution to the requests option, we would certainly want to keep this conversation going in the future when another sprint is being planned. One question we have is: how easily could we "turn off" or "hide" this request button after 1.0.0 goes live? @ggeisler We would want to retrofit our existing solution into our own instance of 1.0.0 until a future dev cycle works on this.

A couple of things to note for future dev and design work:
- It would be great if the requests button could appear based on an institution's own needs - aka dependent on component level requesting per institution. We request things by the box here, so anything that doesn't have a box or equivalent container  wouldn't get a request button (like a series, subseries, or collection). Other institutions probably request things by the folder, others by the collection, etc.
- Being able to de-duplicate requests would be very important for us and maybe others. If you have a user requesting the same "Box 1" in a collection because they click the "Request" button on every item, that ends up with a lot of unnecessary requests and backend messiness.

**Comment by ggeisler** [comment]
I'm closing this because I believe the main goal of the ticket has been completed, and the discussion of the request button is resolved/maintained by #1258 and #1259. 

Thanks the input @seanaery and @crugas.
