### ISSUE TITLE
Component view layout update: Collection info

### ISSUE THREAD

**Issue by ggeisler** [projectblacklight/arclight#1175]
One of the UI updates noted in https://github.com/projectblacklight/arclight/issues/1148 involves the collection information box, which is currently on the top right of any collection or component page: 

<img width="975" alt="Screen Shot 2022-10-13 at 4 09 09 PM" src="https://user-images.githubusercontent.com/101482/195726870-3c2c0ef0-c532-424e-aa23-4996ea43a37b.png">

In the revised layout, the proposal is to move this box to the top of the sidebar column, with some changes to the components of the box:

<img width="1198" alt="Screen Shot 2022-10-13 at 4 12 48 PM" src="https://user-images.githubusercontent.com/101482/195727301-66897e82-1d94-49f2-9eb7-150bff19494c.png">

## Box styling recommendations
We can start with the current box color and border but adjust the text:
- `Collection` heading: `h3` at `22px` (`1.375rem`), medium weight
- Title of the collection: regular paragraph text at `1rem` medium weight

## Collection ID
Remove this because it is now displayed as part of the collection admin metadata dropdown, described at the end of this ticket.

## Bookmark checkbox
Remove this because it is now displayed next to the collection/component title.

## Request button
- Size: `btn-sm`
- Color: `primary` (the presence and use of this button is likely to vary a lot between institutions, so this is basically just a placeholder)

## Download button
This is a significant change from the existing download links. The issue here is I think we want to keep the collection info box as compact as possible so it doesn't take unnecessary vertical space away from the other, likely more frequently-used sidebar sections. The challenge is, what is downloadable for a given collection is highly variable, depending on the institution policies and what might have been created for a given collection. In our last ArcLight workcycle it seemed that most collections had either a PDF of the finding aid, an XML of the EAD, both, or neither. So the proposal (which is certainly open to other ideas) here is:

If there are no downloads for a collection, don't show a download button:

<img width="397" alt="Screen Shot 2022-10-13 at 4 33 46 PM" src="https://user-images.githubusercontent.com/101482/195730030-f6d75118-cc20-4f83-aed2-ad1c0be1ae12.png">

If there is more than one download available for the collection, show a "Download" dropdown, with each download option in the dropdown menu (ideally using the icons we currently use for the download links; the icons in the mockup are just placeholders for the PDF/XML icons):

<img width="397" alt="Screen Shot 2022-10-13 at 4 36 28 PM" src="https://user-images.githubusercontent.com/101482/195730339-374977c3-fa93-4ebc-9811-7cf4b1b769d0.png">

If there is only one download available for a collection, use a button rather than a dropdown (again, using the current icons rather than the plus icon shown here):

<img width="397" alt="Screen Shot 2022-10-13 at 4 37 41 PM" src="https://user-images.githubusercontent.com/101482/195730440-90a7019c-bcd1-4351-9b64-3eef3776c950.png">

---

<img width="397" alt="Screen Shot 2022-10-13 at 4 37 56 PM" src="https://user-images.githubusercontent.com/101482/195730458-94e61074-d92b-4962-9cf8-0fe4c613fac9.png">

---

For both the button and the dropdown approaches, the component color is `secondary`.

## Collection admin information dropdown
This is also a new addition, inspired by Duke's implementation. Using a dropdown to display the collection ID saves space in the collection info box and also enables us to display more potentially helpful collection admin metadata. The exact metadata available and appropriate for this dropdown box is partially dependent on the implementing institution (institutions will likely differ in what sort of related IDs and catalog links make sense for their systems and practices). For example, here's what Duke shows for a typical collection:

<img width="367" alt="Screen Shot 2022-10-13 at 3 43 22 PM" src="https://user-images.githubusercontent.com/101482/195731605-a09bddc4-7240-461f-b570-8e6b58a95dc0.png">

In the mockup below I included the metadata elements I thought most likely to be available based on the collection indexing alone, but I am making some assumptions. Plus, there might be other useful admin metatdata that is reliably available for us to display here that I didn't include, so whoever works on this should feel free to suggest other potential things we could display. The general idea is that we provide a panel with basic collection admin metadata that implementers will likely supplement with additional local metadata.

<img width="948" alt="Screen Shot 2022-10-13 at 4 49 53 PM" src="https://user-images.githubusercontent.com/101482/195732044-3e13fbcd-aad4-4404-a2b8-7511726ee2b3.png">

**Comment by marlo-longley** [comment]
Following up on this big UI ticket, it seems like the majority of work is done, the box is in place with working i icon/info, and now we are working out the details of:

- Moving the request button (https://github.com/projectblacklight/arclight/issues/1174)
- Configuring XML for download (https://github.com/sul-dlss/nta-arclight/issues/127)

**Comment by jcoyne** [comment]
@marlo-longley as this is arclight, we probably don't want to consider NTA tickets as part of this.

**Comment by marlo-longley** [comment]
Complete!
