### ISSUE TITLE
View more/less display is inconsistent in context navigator

### ISSUE THREAD

**Issue by marlo-longley** [projectblacklight/arclight#1198]
Here are some different screenshots of issues I'm seeing

1. "view more" not displaying at top level when collapsed
<img width="477" alt="Screen Shot 2022-10-18 at 14 01 41" src="https://user-images.githubusercontent.com/1328900/196509252-e408c52c-c0e4-4bf8-8b8d-0a28d31e860b.png">

2. If I click the plus sign and expand "view more" still not displaying
<img width="468" alt="Screen Shot 2022-10-18 at 13 39 29" src="https://user-images.githubusercontent.com/1328900/196509544-95e4d0b2-5adf-4023-8677-68a26164acec.png">

3. If I now click an individual item (Karl DOENITZ No. 2) I see some strange indentation between No. 1 and No. 2, and I see an unstyled "Expand" button underneath the collection description
<img width="514" alt="Screen Shot 2022-10-18 at 14 01 55" src="https://user-images.githubusercontent.com/1328900/196509598-ceba4b85-43a9-4123-84c6-288f859330b1.png">

**Comment by marlo-longley** [comment]
TODO: Marlo figure out if we will have series descriptions
Update data in ASpace if so

**Comment by thatbudakguy** [comment]
fake text would be awesome, if you don't mind

**Comment by cbeer** [comment]
I thought Gary's designs removed descriptions from this hierarchy display?

**Comment by ggeisler** [comment]
That is true, but given we have a new plan for more series', I thought it might be worth keeping those descriptions in and see how useful they seem with whatever series descriptions we get.

**Comment by jcoyne** [comment]
Yeah, I believe this ticket was created before @cbeer implemented those changes.
