### ISSUE TITLE
Resizing the page breaks the "view more" link

### ISSUE THREAD

**Issue by jcoyne** [projectblacklight/arclight#1235]
The link no longer does the open and close.

**Comment by thatbudakguy** [comment]
guess that means https://github.com/projectblacklight/arclight/blob/19f35ffff3dafd65624d0793a7885f7b433efc02/app/assets/javascripts/arclight/truncator.js#L28-L31 isn't working

**Comment by jcoyne** [comment]
@thatbudakguy isn't it also possible this is setting up multiple listeners (a new one on each resize), which could be conflicting?

**Comment by thatbudakguy** [comment]
probably — is this a case where we want `once: true`?

**Comment by thatbudakguy** [comment]
i guess what we want is "ensure the listener is set, but don't set it more than once" rather than "prevent the listener from being invoked more than once"

**Comment by thatbudakguy** [comment]
```js
button.onclick = () => container.classList.toggle('expanded')
```
might do that
