### ISSUE TITLE
Collection ID changes incorrectly

### ISSUE THREAD

**Issue by ggeisler** [projectblacklight/arclight#1241]
Perhaps this will be resolved in the related PR #1221, but just in case:

The collection ID displayed in the Collection information box changes at different levels of the content inventory when it should always be the same ID.

For example, a couple of levels deep we see this collection ID (though at this level the field label is omitted):

<img width="952" alt="Screen Shot 2022-10-27 at 2 04 59 PM" src="https://user-images.githubusercontent.com/101482/198398617-a8ccb025-fe39-410b-a23d-b9af70bf5c30.png">

---

Up one level we see a different one:

<img width="952" alt="Screen Shot 2022-10-27 at 2 05 18 PM" src="https://user-images.githubusercontent.com/101482/198398600-6defba1f-8fab-4295-b642-fc942f6c1b6b.png">

---

And finally at the top, collection level, we see what I think it the correct ID that we should always see here:

<img width="952" alt="Screen Shot 2022-10-27 at 2 05 32 PM" src="https://user-images.githubusercontent.com/101482/198398588-03cdcbf2-1400-41ac-8024-148417f67d0c.png">

---

This collection information box is for collection-level info and should be static for a given collection; nothing in it should change based on what level of the content inventory we're currently in.

**Comment by jcoyne** [comment]
@ggeisler as you said, I think this is resolved via https://github.com/projectblacklight/arclight/pull/1221.  Can you confirm that?

**Comment by ggeisler** [comment]
@jcoyne Yep, looks good now.
