### ISSUE TITLE
Everytime forward or back link is used another checkbox appears

### ISSUE THREAD

**Issue by jcoyne** [projectblacklight/arclight#1251]
<img width="808" alt="Screenshot 2022-10-31 at 4 34 22 PM" src="https://user-images.githubusercontent.com/92044/199114823-9703ec4f-ce38-4ac8-83c5-0bb3543c1955.png">

This is a problem in Blacklight. See https://github.com/projectblacklight/blacklight/issues/2860

**Comment by marlo-longley** [comment]
Closed by https://github.com/projectblacklight/blacklight/issues/2860
