### ISSUE TITLE
Relocate Request button

### ISSUE THREAD

**Issue by ggeisler** [projectblacklight/arclight#1258]
There's a fair amount of history motivating this in the comments of #1174. The gist of it is in the recent UI reorganization we moved the grouping of collection-related info into a "Collection" box at the top of the left-hand sidebar. In my mockups I suggested that box include the Request button. I didn't, however, take into account that Requests can potentially be made at all levels of the inventory hierarchy (depending on the collection and the implementing institution's practices). Its new location in the Collection box is really only appropriate if requests are only made at the collection-level.

I suggest we relocate the Request button to the title/Bookmark area of the collection/component page, as shown in the mockups below. That should make the button more clearly associated with the current component. At this stage, I think that's all we do, and it is up to the implementer to decide whether to display the button at various levels of the inventory, or whether to display it at all, and how to hook it up to their particular request process. The end result is essentially the same as ArcLight before the UI reorganization, so I don't think we're really changing any functionality, just moving the button back to where it used to be, more or less.

Note that in the #1174 discussion @crugas mentioned:

> how easily could we "turn off" or "hide" this request button after 1.0.0 goes live? We would want to retrofit our existing solution into our own instance of 1.0.0 until a future dev cycle works on this.

Whoever implements this please note that. But @crugas I don't expect that to be a problem, since for Stanford's current ArcLight implementation we will want to hide the request button ourselves (this is a single collection instance where requests are not applicable). So we should have that figured out before you need to deal with it.

Examples of new location of Request button:

### Collection-level
<img width="1010" alt="199121493-959fcce6-1d10-4216-b6a8-43f240136731" src="https://user-images.githubusercontent.com/101482/199361095-5c32cad8-be4e-48d9-b31f-f6e2c373427e.png">

### Series-level

<img width="1010" alt="199121546-662d4a56-bf67-465f-b581-fe599b37f984" src="https://user-images.githubusercontent.com/101482/199361100-c79f8e71-27c8-4222-a0bc-3aafa5422866.png">

### File-level

<img width="1010" alt="199121580-c2cb318e-9095-4dc3-8f84-eb7f6ac13271" src="https://user-images.githubusercontent.com/101482/199361107-96341a69-3ca0-47b2-95a8-3cd8bbe8fa86.png">

**Comment by crugas** [comment]
Thanks for opening and detailing this issue! I look forward to having future conversations about building this feature out. It's also good to hear that Stanford will also be hiding this button, so we won't be the only ones trying to figure it out.

**Comment by jcoyne** [comment]
I believe this is done.
