### ISSUE TITLE
Update "Contents" section of parent component page

### ISSUE THREAD

**Issue by ggeisler** [projectblacklight/arclight#1267]
It looks like something that didn't make it over in the recent UI redesign is the bookmarks for items in the Contents section of a parent component page. The current layout right-aligns the Box/Folder info and omits the bookmark controls:

<img width="1178" alt="Screen Shot 2022-11-02 at 5 22 33 PM" src="https://user-images.githubusercontent.com/101482/199627019-628373f4-7fb6-4e38-9168-6946174c5cb2.png">

---

I believe we want something like this, where the bookmark controls are present for each item (right-aligned) and the box/folder info is left-aligned, similar to the search result item layout:

<img width="1010" alt="Screen Shot 2022-11-02 at 5 23 31 PM" src="https://user-images.githubusercontent.com/101482/199626959-cbf55b45-5d5c-48e5-b849-f72ed730e1d4.png">

**Comment by jcoyne** [comment]
It looks like this was lost here: https://github.com/projectblacklight/arclight/commit/31e97fc1dc9993826476118ce50f28222e4588c4#diff-42cafe5f907a7e34f32b22bbf0b31c661b9e18fedc265a974898bc9224860f0eL48

**Comment by jcoyne** [comment]
@ggeisler where does the online icon go in this context?

**Comment by ggeisler** [comment]
@jcoyne Just to the left of the bookmark element:

<img width="114" alt="Screen Shot 2022-11-17 at 11 42 44 AM" src="https://user-images.githubusercontent.com/101482/202531239-e98774b1-b582-4428-b131-ed791322ef15.png">

I'm not sure if we already have some left margin on the bookmark element in that context, but if not, I'd guess `margin-left: 0.25rem` on it would be about right (I think we should add the margin to the bookmark rather than the icon so that if someone chooses not to use the bookmark controls, the icon will still align at the right side of the row).
