### ISSUE TITLE
Component URLs should separate the ead & ref slugs

### ISSUE THREAD

**Issue by seanaery** [projectblacklight/arclight#1318]
## Summary
ArcLight currently creates URLs to individual components like this:
`{host}/catalog/{ead_ssi}{ref_ssi}`

So we get URLs like:
**Collection:** `archives.institution.edu/catalog/slug`  <-- _this is OK_
**Component:** `archives.institution.edu/catalog/slugaspace_123` <-- _this is not ideal_

## Desired Change
This ticket is a request to improve the component URLs by using one of these conventions instead:
`archives.institution.edu/catalog/slug/aspace_123`
`archives.institution.edu/catalog/slug_aspace_123`

## Reasons for concern over the smooshed together URL
- Sometimes creates awkward unintended words (in practice, `ead` slugs often end in letters and `ref` values often begin with `al` or `aspace`
- Harms SEO, i.e., makes it harder to Google using the EAD slug
- Can make web analytics reports on per-collection activity harder to parse
- Makes it harder to build future pattern-based redirects _from_ these URLs to new ones
- Not very readable

### No separation in Component URL
These apps follow default core:
- [Albany](https://archives.albany.edu/description/catalog/apap106aspace_ca37199989c630810eaf9d88b627568e)
- [CAO](https://archives.library.wcsu.edu/caoSearch/catalog/RG032al_4b64305abfd02690cc2b444fefa39b3901fd8b8c)
- [EmpireADC](https://www.empireadc.org/search/catalog/nsyu_ny_censusal_4bf70b448ac8351a147acff1dd8b1c0b9a791980)
- [Indiana](https://archives.iu.edu/catalog/InU-Li-VAE1172aspace_35f347edca5768fe625ad93e137413f4)

### Has separation in Component URLs by wedging an underscore between the `ead` & `ref` slugs
These apps wedge an underscore between the `ead` & `ref` slugs (overriding core):
- [Duke](https://archives.lib.duke.edu/catalog/womantheworldover_aspace_14792452e1b28986b7ca542c95e29990)
- [Michigan](https://findingaids.lib.umich.edu/catalog/umich-bhl-85203_aspace_9dd29079986e11b7e7bee6321e6099ba)
- [Princeton](https://findingaids.princeton.edu/catalog/WC064_c3340)

## Other Considerations
@gwiedeman &  @jrochkind astutely note on `code4lib#arclight` Slack that if a change is made to core, it's important to be able to redirect from the old style to keep existing URLs working. And even if core stays how it is, I recommend making the convention configurable or otherwise straightforward to override globally.

**Comment by cbeer** [comment]
https://github.com/projectblacklight/arclight/pull/1317 is an idea for a seam for downstream applications to decide what style they want 🤷‍♂️

**Comment by jrochkind** [comment]
> Harms SEO, i.e., makes it harder to Google using the EAD slug

It's a bit of an esoteric art and I'm not necessarily an expert, but I believe that `/slug/aspace_123` will do a lot better than `/slug_aspace_123` with regard to that.

**Comment by seanaery** [comment]
@marlo-longley We are definitely still interested in prioritizing this work. In lieu of having a configurable way to do this, here's what we ended up having to modify in our local 1.0.1-based app:
* Override the `to_field 'id'` from `ead2_component_config.rb` to join the two parts with an underscore ([commit](https://gitlab.oit.duke.edu/dul-its/dul-arclight/-/commit/f30720665117c2e1dad9d2a96211c61c23071312)). This takes care of most of the logic for a component URL, tbh, and wasn't too heavy a lift, but...
* Fix the **breadcrumb** links to parent components ([commit](https://gitlab.oit.duke.edu/dul-its/dul-arclight/-/commit/4f324e7910cf60e0cbec582e913a8ecf7b676f6c
)). This was more of a pain and required several local overrides, esp. stemming from the use of `app/models/arclight/parent.rb` which includes a method `global_id` that assumes the component ID is `"#{eadid}#{id}"`
