### ISSUE TITLE
Creator field is missing from component display

### ISSUE THREAD

**Issue by seanaery** [projectblacklight/arclight#1432]
In the `CatalogController`, the Creator field (`creators_ssim`) is correctly configured to display on a collection page as a "Summary" field:
https://github.com/projectblacklight/arclight/blob/main/lib/generators/arclight/templates/catalog_controller.rb#L265

However, Creator is currently missing from display on a component page. It is already indexed on the component level, it just needs to get added to the component metadata display via
`config.add_component_field` .

E.g., for [this component](https://arclight-demo.projectblacklight.org/catalog/rushbenjaminandjuliaaspace_43c9e6c4a080a76a450f8ef1ae2f99d7):
<img width="1181" alt="Screenshot 2023-12-04 at 12 52 33 PM" src="https://github.com/projectblacklight/arclight/assets/3933756/f784e69b-34b8-43c4-95f2-a89974a6f1fe">

**Comment by gwiedeman** [comment]
It looks like this happens on the demo site, but not on the creator links for [Michigan's](https://findingaids.lib.umich.edu/catalog/ehll--saginawsteering) or [Princeton's](https://findingaids.princeton.edu/catalog/AC329) instances, which work as I would expect without the `&search_field=all_fields` param, so its unclear to me whats going on here.

**Comment by seanaery** [comment]
@gwiedeman I think that's the in-progress known issue #1422 at work there...
