### ISSUE TITLE
Containers display should only capitalize the first character without changing the case of subsequent characters

### ISSUE THREAD

**Issue by seanaery** [projectblacklight/arclight#1433]
When containers get displayed, ArcLight core intends to capitalize them, e.g., where `box 1` may be indexed, it should display as `Box 1`. The current solution works OK for containers like that. It uses the ruby `.capitalize` method. 
https://github.com/projectblacklight/arclight/blob/main/app/models/concerns/arclight/solr_document.rb#L113-L116

But `.capitalize` is problematic for containers like `box MN6` because it turns them into `Box mn6`; it lowercases all characters after the first one.

**Comment by mmmmcode** [comment]
@randalldfloyd FYI I seem to remember the IU Archives reporting this bug to DCS (boxes with indicators like OS1 or SC1 would end up being lowercase on the arclight site)
