### ISSUE TITLE
Allow for physdesc elements that are not extent

### ISSUE THREAD

**Issue by marlo-longley** [projectblacklight/arclight#1448]
For example
[physfacet](https://www.loc.gov/ead/tglib/elements/physfacet.html)
[dimensions](https://www.loc.gov/ead/tglib/elements/dimensions.html)

This ticket covers indexing, display, and formatting.

This ticket is broken out from #898

**Comment by randalldfloyd** [comment]
Our customizations at IU assume that all child elements are excluded while indexing `physdesc`, and that the indexing/display of those children are handled individually elsewhere.   So our indexing for collection and component skips the individual elements like:
```
to_field 'physdesc_ssm', extract_xpath('/ead/archdesc/did/physdesc', to_text: false) do |_record, accumulator|
  accumulator.map! do |element|
    physdesc = []
    element.children.map do |child|
      next if child.class == Nokogiri::XML::Element
...
```
And then lots of logic scattered about to pick up the child elements...
```
to_field 'physfacet_ssm', extract_xpath('/ead/archdesc/did/physdesc/physfacet')
to_field 'dimensions_ssm', extract_xpath('/ead/archdesc/did/physdesc/dimensions')
to_field 'extent_ssm', extract_xpath('/ead/archdesc/did/physdesc', to_text: false) do
    (logic to pick out just the extent elements...)
...

to_field 'physfacet_ssm', extract_xpath('./did/physdesc/physfacet')
to_field 'dimensions_ssm', extract_xpath('./did/physdesc/dimensions')
to_field 'extent_ssm', extract_xpath('./did/physdesc', to_text: false) do
    (logic to pick out just the extent elements...)
```

And then the individual fields above are used directly in the catalog controller to add to summary and component fields.

**Comment by randalldfloyd** [comment]
@seanaery Just making sure I understand your implementation correctly...

You are essentially just getting the text only out of `physdesc` directly and then also the text out of its child elements, but then the accessor subtracts any values found from the separate `extent` field.  The catalog controller receives the resulting array of text values and applies format per the the defined summary/component field definitions (the separator etc.)

So in the end you have a single field in the display, and all values are contained there with no inner labeling of where those values originally came from (i.e. physfacet vs. dimensions etc.)

The difference with IU is direct access of those child elements, which are labeled separately.  Just wondering how to resolve questions of granularity like this for core default behaviors.

**Comment by seanaery** [comment]
That's exactly correct @randalldfloyd -- that how ours currently works (this was a change we made in our recent upgrade). The way you have physdesc & descendants set up at IU seems more appropriate for the core engine than our setup is, I think.

I'm tagging @mmmmcode for her thoughts on this as well. Your IU code might even be preferable for Duke's site. It does give you more granular control over those different elements...
