### ISSUE TITLE
Render altformavail at the component level

### ISSUE THREAD

**Issue by marlo-longley** [projectblacklight/arclight#1450]
Currently we only display this at the collection level.
We have it indexed but not displayed at the moment.

Add an `add_component_field` line to the catalog controller.

This ticket is broken out from #898

**Comment by gwiedeman** [comment]
Added to fixtures at http://localhost:3000/catalog/umich-bhl-851981aspace_7a47b946a5107eb56d93ef0cd069d568

**Comment by marlo-longley** [comment]
I see that this was added to the fixture data in #1466 :
`https://media.dlib.indiana.edu/media_objects/pv63gh62z`

It is being indexed, and when I search this string, I do have a hit and am taken to a component. 
However, the component does not display the link.
I'll look into this a little further

<img width="1489" alt="Screenshot 2023-12-15 at 12 12 32 PM" src="https://github.com/projectblacklight/arclight/assets/1328900/2b004e88-af64-4586-850c-c5c05bb660a5">

<img width="982" alt="Screenshot 2023-12-15 at 12 12 39 PM" src="https://github.com/projectblacklight/arclight/assets/1328900/8d4fb138-4919-475b-abe8-788c089a5cbe">

**Comment by gwiedeman** [comment]
Maybe it should be encoded differently in the fixtures as a link now that #1449 has been addressed?

**Comment by gwiedeman** [comment]
This is actually the same suffix issue as `<odd>`. I'll put in a PR to fix the rest.
