### ISSUE TITLE
Handle bioghist at collection and component levels

### ISSUE THREAD

**Issue by marlo-longley** [projectblacklight/arclight#1452]
[bioghist](https://www.loc.gov/ead/tglib/elements/bioghist.html)

We are already indexing this field into the searchable text fields bucket on the collection level.

Tasks

 - [x] Display at the collection level
 - [x] Index at the component level
 - [x] Display at the component level

This ticket is broken out of https://github.com/projectblacklight/arclight/issues/898

**Comment by gwiedeman** [comment]
Will soon display in component level and added example to fixtures: http://localhost:3000/catalog/aoa271aspace_563a320bb37d24a9e1e6f7bf95b52671

**Comment by marlo-longley** [comment]
Confirmed this is not displaying at the collection and component level, closed by https://github.com/projectblacklight/arclight/pull/1466/files
