### ISSUE TITLE
Index and render index / indexentry fields

### ISSUE THREAD

**Issue by marlo-longley** [projectblacklight/arclight#1453]
Duke has a solution for this locally that we can reference.

This ticket is broken out of https://github.com/projectblacklight/arclight/issues/898

**Comment by seanaery** [comment]
Our solution at Duke (which we would be happy to PR to core) is to turn these elements into HTML tables. See `format_indexes` & `format_indexentries`...

https://gitlab.oit.duke.edu/dul-its/dul-arclight/-/blob/main/app/helpers/ead_format_helpers.rb#L38
https://gitlab.oit.duke.edu/dul-its/dul-arclight/-/blob/main/app/helpers/ead_format_helpers.rb#L77-102

Examples in action:
https://archives.lib.duke.edu/catalog/jwtnewsletters#other-indexes
https://archives.lib.duke.edu/catalog/gilpin#other-indexes

**Comment by seanaery** [comment]
EAD2002 docs re:
`<index>`: https://www.loc.gov/ead/tglib/elements/index-element.html
`<indexentry>`: https://www.loc.gov/ead/tglib/elements/indexentry.html
