### ISSUE TITLE
Display <odd> 

### ISSUE THREAD

**Issue by marlo-longley** [projectblacklight/arclight#1456]
This is a widely used field.

This ticket is broken out of https://github.com/projectblacklight/arclight/issues/898

**Comment by marlo-longley** [comment]
In searching the codebase I am not finding any `<odd>` in our fixture data. I think this needs further confirmation that it is being displayed.

**Comment by gwiedeman** [comment]
There is an `<odd>` here: https://github.com/projectblacklight/arclight/blob/91420125acc80381502a8b0996b39b931f3bf4aa/spec/fixtures/ead/nlm/alphaomegaalpha.xml#L77

But I didn't add tests for these, which could be useful.

**Comment by marlo-longley** [comment]
Thank you!! Oops.
