### ISSUE TITLE
Display <custodhist> at the component level

### ISSUE THREAD

**Issue by marlo-longley** [projectblacklight/arclight#1462]
[custodhist](https://www.loc.gov/ead/tglib/elements/custodhist.html)

Broken out of #898

**Comment by gwiedeman** [comment]
This one is also already displaying: https://github.com/projectblacklight/arclight/blob/main/lib/generators/arclight/templates/catalog_controller.rb#L327

However, both `<custodhist>` and `processinfo` (#1463) are using `_html_tesm`, so I'm wondering @seanaery if you found examples where the tags within them were something more elaborate than `<p>`s and they wouldn't display? It looks [like ](https://github.com/projectblacklight/arclight/blob/main/lib/arclight/traject/ead2_component_config.rb#L260)this would index whatever, but I wonder if there are cases where odd XML wouldn't display in a browser?

**Comment by seanaery** [comment]
@gwiedeman As far as I can tell, all our Duke finding aids that have `processinfo` or `custodhist` are composed entirely of `head` & `p` tags, BUT I do see that either of those elements by EAD2002 specs _can_ contain elements like `chronlist` that we have other special formatting rules for, so it may be safest to leave those elements capturing the raw XML and piping them through the `render_html_tags` helper.

**Comment by gwiedeman** [comment]
Ah, I get what that's doing now. I'll have to update #1466 next week then.

**Comment by gwiedeman** [comment]
This is safe to close then,
