### ISSUE TITLE
Display <processinfo> at component level

### ISSUE THREAD

**Issue by marlo-longley** [projectblacklight/arclight#1463]
[processinfo](https://www.loc.gov/ead/tglib/elements/processinfo.html)

Broken out from #898

**Comment by gwiedeman** [comment]
This should already be displaying with https://github.com/projectblacklight/arclight/blob/main/lib/generators/arclight/templates/catalog_controller.rb#L328

**Comment by seanaery** [comment]
@gwiedeman Yep, excellent. We must've just missed that this morning when reviewing the tags. Let's close this out!
