### ISSUE TITLE
Question about has_online_content_ssim indexing rule

### ISSUE THREAD

**Issue by elohanlon** [projectblacklight/arclight#1558]
Hello,

Just writing in with a question.  While working on our Arclight app, we noticed that Arclight currently uses an "_ssim" field for something that appears to index a single boolean value (wrapped in an array):

`https://github.com/projectblacklight/arclight/blob/a49ae6af6739f79844f067067552b9fd32198ad3/lib/arclight/traject/ead2_component_config.rb#L210`

Is _ssim is preferred by the Arclight maintainers in cases like this, rather than something like a _bsi ("boolean stored indexed") field?  Although there isn't currently a _bsi field defined in the example solr schema.xml file (`https://github.com/projectblacklight/arclight/blob/a8dc92f7b0c852bdef7f5ab838c97aec6c75c1bc/solr/conf/schema.xml`), one could be added.

We have a similar indexing case for another field, so I thought it would be good to ask this here, in case there are any advantages to _ssim that I hadn't thought of.

Thanks!

**Comment by elohanlon** [comment]
Hi again.  Just following up on this GitHub Issue since it's been a couple of months.  Would anyone on the Arclight development team be able to share thoughts on this?

**Comment by corylown** [comment]
My take is it's easier to manage data types in the application code rather than Solr _and_ the application code. It's simpler to know you're always dealing with an array from Solr and can coerce the data as needed at the app level where it's being used.

**Comment by corylown** [comment]
@elohanlon may I close this issue?

**Comment by elohanlon** [comment]
@corylown Thank you for your reply!  (And for the discussion in today's Arclight community call!)

Feel free to close!
