### ISSUE TITLE
Move from results inside a finding aid or digitized item metadata to other search and browse options for related collections or through access points

### ISSUE THREAD

**Issue by anarchivist** [projectblacklight/arclight#18]
* Ref: req 1.23
* Category: 1. Core Discovery
* Subcategory: Navigation

**Comment by seanaery** [comment]
Resolving this issue as part of a review of `arclight 1.0.x`. The UI links metadata values on collection/component show pages to see related materials. Breadcrumb and facet links also lead to related materials. Related Materials section elements (`relatedmaterial`, `separatedmaterial`, `otherfindaid`, `altformavail`, `originalsloc`) also render for explicitly encoding links to other finding aids or resources. This will improve further upon completion of #898 e.g., with formatting for links encoded as `extref`.
