### ISSUE TITLE
Visual representation of levels

### ISSUE THREAD

**Issue by anarchivist** [projectblacklight/arclight#193]
Following the mockups, we need a set of placeholders to represent the various levels of hierarchy across ArcLight. The representations represented in the mockups are a starting point, and probably merit further discussion, but this is a starting point to make sure they are accommodated by a basic implementation. We should probably discuss this with @ggeisler soon.

**Acceptance criteria**

* Four levels of placeholders to represent levels of description, implemented as SVG graphics
    * _A_ Collection
    * _B_ Intermediate level node (often series)
    * _C_ Intermediate level node, subordinate (often subseries)
    * _D_ Terminal node (often, but not necessarily item)
* Present the images in partials defined in #190 and #192 

**Notes**

* In my understanding, the squares in the mockup do not represent the number of levels of description.
* The placeholders will be used widely throughout ArcLight, both in search results and in the inventory views.

**Mockups**

![arclight-mockups-mvp](https://cloud.githubusercontent.com/assets/73732/25363321/72b7c248-290e-11e7-8c65-959a350d2335.jpg)

![screen shot 2017-04-24 at 4 49 33 pm](https://cloud.githubusercontent.com/assets/73732/25363322/72bc149c-290e-11e7-9a4e-81681e830185.png)

**Comment by anarchivist** [comment]
Closes #16

**Comment by anarchivist** [comment]
Ref #715, #669. This currently is only implemented for search results.

**Comment by ggeisler** [comment]
I believe we now have a consistent pattern (using the repository, collection, container, and file level icons) in place throughout the application so am closing this.
