### ISSUE TITLE
Should we remove index field config from catalog_controller?

### ISSUE THREAD

**Issue by mejackreed** [projectblacklight/arclight#211]
We seem to have have deviated from this Blacklight pattern now. Should we just remove these to reduce confusion?

**Comment by jkeck** [comment]
👍

**Comment by jkeck** [comment]
Alternatively, we could configure the 3 fields to use the accessor we've set-up, configure helper methods to render the content tags instead of the standard `dl`.  ¯\\_(ツ)_/¯

**Comment by mejackreed** [comment]
I guess the question too is what should be configurable by an ArcLight adopter?

**Comment by seanaery** [comment]
Resolving this issue as part of a review of `arclight 1.0.x`. The `CatalogController` in v1 uses `config.add_index_field` intentionally.
