### ISSUE TITLE
Switch breadcrumb implementations to using Bootstrap breadcrumb

### ISSUE THREAD

**Issue by mejackreed** [projectblacklight/arclight#213]
Didn't realize this was a thing: https://v4-alpha.getbootstrap.com/components/breadcrumb/

**Comment by mejackreed** [comment]
I'm giving this a shrug now, as our breadcrumb design isn't compatible with the bootstrap one without hacking it. Thoughts? @ggeisler @jvine ?

**Comment by ggeisler** [comment]
@mejackreed In what way is our design not compatible with Bootstrap?

It seems like it would be nice to use the Bootstrap breadcrumbs, because it would be documented, managed approach, but it also isn't critical at all from a UX point of view, so I wouldn't think we'd want to compromise our design just to be able to use the Bootstrap way.

**Comment by mejackreed** [comment]
Bootstrap uses the trailing `/` rather than the `>>` it also adds a wrapper div around that is colored/styled.

**Comment by jvine** [comment]
Is the only difference that we use &raquo; in place of the slash? That switch would be okay with me if @ggeisler likes it.

**Comment by ggeisler** [comment]
@mejackreed Oh, if that's all it is that doesn't really seem to be a big deal. As JV says, using the `/` is fine. And I would think we can address the styled wrapper div through CSS.

**Comment by anarchivist** [comment]
We can indeed change back to &raquo; if we wanted through CSS.

**Comment by mejackreed** [comment]
So it seems like a lot of work to hack around Bootstrap just to get it to display the way it currently is. I'd vote to kick this to the backlog as the initial intent here was to reduce code to maintain.

**Comment by anarchivist** [comment]
I'm pretty neutral and don't care which delimiter we use. 😸

**Comment by mejackreed** [comment]
Closing for now. New designs forthcoming
