### ISSUE TITLE
Component detail page: where to display children of current component?

### ISSUE THREAD

**Issue by anarchivist** [projectblacklight/arclight#327]
Given a component with children:

* The component's children don't display on the component detail page.
* The only place to view the component's children is from the full content inventory.

Where can we accommodate a display of children in this context?

**Screenshot**

![screen shot 2017-05-15 at 11 41 48 am](https://cloud.githubusercontent.com/assets/73732/26073367/80e342ec-3963-11e7-9833-f99bf6011d7d.png)

**Comment by ggeisler** [comment]
Do we need to show the component's children on this page? To get to this page the user has made a conscious choice to view this component, so maybe providing direct access to its children is not essential?

A user curious about the component's children could select the "View complete contents list" button, which probably should link to the inventory at the location of the current component, so its children would be somewhat readily accessible, if the user recognizes what that button affords them.

![arclight-mockups-mvp_pdf__page_12_of_23_](https://cloud.githubusercontent.com/assets/101482/26115905/38eec46c-3a16-11e7-876a-ba549afe0697.png)

**Comment by anarchivist** [comment]
Just noting that we had some converation about this in the context of #231 as well on the 5/17 standup.

**Comment by seanaery** [comment]
Resolving this issue as part of a review of `arclight 1.0.x`. Child components are now displayed both in the sidebar hierarchy navigator and in tabular form in the body of a component show page.
