### ISSUE TITLE
Group by collection

### ISSUE THREAD

**Issue by anarchivist** [projectblacklight/arclight#369]
**Acceptance criteria**

On the search results view:

* Add a new option to be able to group by collection 
* When "group by collection" is active, group all search results by the collection within which they appear

**Discussion**

* Is the order significant? 
* How much detail should be shown for each?
* Is hierarchical view out of scope for this?

**Mockup**

![arclight-mockups-mvp](https://cloud.githubusercontent.com/assets/73732/26333949/848001f2-3f16-11e7-8026-17a924cbc94b.jpg)

**Comment by anarchivist** [comment]
First pass:

* List "matching" collections and all components that match

**Comment by mejackreed** [comment]
Some notes here on problems encountered (and some solutions!):

 - To enable grouping in Solr we need to set that on an indexed, non-multivalued field. (we currently do not have these available for collection) (this isn't a huge task) See: https://github.com/sul-dlss/arclight/commit/888e3a68f21cf04595bc9f7137578b98bc9f2d32

 - Blacklight "default" grouping does not work out of the box https://github.com/projectblacklight/blacklight/wiki/Configuration---Results-View#basic-configuration This needs to be configured manually: https://github.com/sul-dlss/arclight/commit/e987a25a505d47e638e8e1826217f50fa6ca3df0

 - Blacklight logic on whether or not to show grouping is wrong (out of date). Fix is here: https://github.com/projectblacklight/blacklight/pull/1712

 - A quick review of https://github.com/projectblacklight/blacklight/blob/master/app/views/catalog/_group.html.erb and I don't think it will be too difficult to get the functionality we are looking for in the UI. It may be a bit different than what the mock shows exactly, but something workable shouldn't be too difficult.

**Comment by anarchivist** [comment]
Cool - that could work. Can you tell me if this is based on a specific query?

**Comment by anarchivist** [comment]
Initial query behavior is in #697. See #681 and #682 for  UX epics.

**Comment by anarchivist** [comment]
Closing because of other inflight tickets.
