### ISSUE TITLE
Update documentation on repository configuration for request form

### ISSUE THREAD

**Issue by anarchivist** [projectblacklight/arclight#389]
From Patrick at RAC: 

> Repository configuration section on the Indexing EAD in ArcLight (https://github.com/sul-dlss/arclight/wiki/Indexing-EAD-in-ArcLight) doesn't match the full configuration in `repositories.yml`. `google_request_url` and `google_request_mappings` are missing, and there is no documentation about what should be in those fields.

**Comment by mejackreed** [comment]
Updated https://github.com/sul-dlss/arclight/wiki/Indexing-EAD-in-ArcLight

**Comment by anarchivist** [comment]
Err, I'm not sure that this is adequate. Can we discuss this more?

**Comment by mejackreed** [comment]
Closing this, now done
