### ISSUE TITLE
Collection detail page: hide "Navigate overview" when switching to contents display

### ISSUE THREAD

**Issue by anarchivist** [projectblacklight/arclight#406]
Per discussion on 5/26 checkin and based on feedback on from the Bentleyw: 

> When browsing ‘Contents’, the left-hand nav menu includes items from the ‘Overview’ menu.

As @ggeisler notes below (he commented when I just wrote a placeholder ticket) this "Navigate overview" block was not intended to show up when displaying the contents.

**Comment by ggeisler** [comment]
Just to be clear, not referring to hiding the "Overview" tab but the "Navigate overview" box in the sidebar. So sidebar when on the Contents tab looks more like this:

![arclight-mockups-end-user-ui_pdf__page_6_of_22_](https://cloud.githubusercontent.com/assets/101482/26507497/6ed4b626-4205-11e7-93e3-e96710403c3f.png)

**Comment by anarchivist** [comment]
Per discussion on 5/26 standup:

* This probably needs some thinking about behavior before we work on it.
* We don't think collapsing the display is adqeuate when switching contexts from the overview display to the contents display.

**Comment by drh-stanford** [comment]
should we move this into design needed?

**Comment by anarchivist** [comment]
Yep - will do. Thanks.

**Comment by ggeisler** [comment]
I believe we can close this since we no longer have a sidebar and the overview navigation is built into the Overview tab, and thus not visible when you are not on that tab, which was the core problem this ticket was created for.
