### ISSUE TITLE
Index components without id attributes 

### ISSUE THREAD

**Issue by anarchivist** [projectblacklight/arclight#446]
Reported by John Rees at NLM. We know that there are a number of institutions that have components that don't have `id` attributes. We should provide a strategy to allow them to be able index their data (perhaps only for testing/dev purposes).

**Acceptance criteria**

- [x] Allow a user to index a finding aid with components that do not contain `id` attributes (maybe a configurable/overrideable strategy for minting the Solr document's ID)
- [ ] Display a warning during the indexing process
- [ ] Document _why_ having components with `id` attributes is recommended

**Comment by drh-stanford** [comment]
I think the one way to support this would to create a tool (rake task) that adds component ids to an EAD that's missing them -- _before_ they are indexed. That way we wouldn't need to change any ArcLight code and keep our rule about requiring component id values. It wouldn't meet the criteria above, but I think it's a workable, and possibly desireable, solution.

**Comment by anarchivist** [comment]
Hm, that's interesting. Do you want me to spin off another ticket for that?

**Comment by jkeck** [comment]
This seems like it might get tricky though.  Will this be a tool that people will use to modify their EADs before indexing them?  Or somehow optionally part of the indexing process?

How would this work with indexing things via URL?  (we download the xml to a tmp file, so it might be workable).

What benefit would modifying a user's XML have over providing an interchangeable ID minting strategy (which may end up being less complicated in the long run).

**Comment by drh-stanford** [comment]
I was thinking about this tool as a stricty pre-processing step that those without ID values would use before indexing. They'd run the tool if an indexing failed due to missing IDs, or if they already know they have missing IDs. I didn't think about indexing from URLs though.

If we want to relax our rules about requiring ID values, then I agree that a minting process built into the indexer would be preferable. My suggestion was to avoid relaxing that rule by providing a pre-processing tool. Thoughts?

**Comment by anarchivist** [comment]
I'm on the fence. I think ideally the experience of being able to test indexing should have minimal barriers, so a minting strategy (with warnings) seems like a good way to go. Other thoughts?

**Comment by John-Rees** [comment]
I like the idea of pre-index minting process, but perhaps not for this MVP. That said, it would be nice to get an error warning if indexing issues are encountered. As it is now the same indexing completed message gets returned regardless.

A short xslt to add <c> IDs and my test indexing went better this time despite some lingering display issues (I had an older release and the upgrade failed last night--a solr_wrapper issue).

Documenting the rationale as to why <c> IDs are required would help.

**Comment by anarchivist** [comment]
Hi @John-Rees - thanks for the feedback! I'm a little surprised to see that the finding aids without `id`s are not throwing errors. When did you last update your local app? 

I've updated the documentation to clarify why IDs are necessary - feel free to provide any additional feedback: https://github.com/sul-dlss/arclight/wiki/Indexing-EAD-in-ArcLight

**Comment by anarchivist** [comment]
Putting this on the docket for our next PO meeting; flagging this for @regineheberlein and @cmkpowell.

**Comment by mejackreed** [comment]
## Update
Acceptance criteria for this actionable work now:

 - [ ] Add a traject setting (false by fault) `DANGEROUSLY_GENERATE_IDS`
 - [ ] `DANGEROUSLY_GENERATE_IDS` should generate an `id` if missing from document or component
 - [ ] Add a log message that this is dangerous and the id's are not persistant

**Comment by anarchivist** [comment]
PO meeting discussion from Monday 8/19:

* The sense from the PO meeting is that ArcLight should still require ID attributes, but and that we should provide a pathway to generate missing IDs with a warning (as described in the comment above).
* This approach is still awaiting feedback from @cmkpowell who needs to get feedback from some of her stakeholers.

**Comment by billdueber** [comment]
Generating the slug as a hash (md5 or sha1 or whatever) based on the absolute xpath to the component in question would make them pretty stable. As long as it doesn't get a direct ancestor, it wouldn't change and the URLs would be at least a *bit* persistent, if not super pretty.

**Comment by anarchivist** [comment]
@billdueber Natively created component IDs in ArchivesSpace (i.e., not those created from importing or migrating data) I believe are created using `SecureRandom.hex`, meaning they are 32 characters; on export, they add a prefix to end up with something like `aspace_8374a4ba5653ee2838a7ca29840c93ec`.

**Comment by cmkpowell** [comment]
Greetings from Virginia Beach.  @billdueber I have emailed Clements and Clarke and asked how frequently they would reorganize the series/subseries in existing finding aids. To me, this seems like an efficient option with acceptable risk, but I am not an archivist.

**Comment by John-Rees** [comment]
FWIW, I generally consider all component parts/descriptive metadata of an EAD to be volatile and untrustworthy. We now rely on external data to generate synthetic ids similar to the hash approach.

**Comment by anarchivist** [comment]
OK, thanks all. @billdueber's approach seems like it might be a good start to generate missing IDs.

**Comment by gordonleacock** [comment]
Here is a little utility I wrote in inject ids in EADs, if that helpful. If not please ignore. One reason for doing this is that not all our libraries use ArchivesSpace.
```
#!/usr/bin/env ruby
require 'optimist'
require 'fileutils'

def eads_revise(original_dir, revised_dir, details=false)
	# Get .xml files in original_dir

  abort "ERROR: --eads=<s> directory not supplied on command line" if original_dir.nil?
  abort "ERROR: --eadsout=<s> directory not supplied on command line" if revised_dir.nil?

	files = Dir.children("#{original_dir}").reject do |f| 
		File.directory?(f) || f[0].include?('.') || f.include?('..') || File.extname(f) != '.xml'
	end

	# create revised_dir unless it already exists
  FileUtils.mkdir_p("#{revised_dir}") unless Dir.exist?("./#{revised_dir}")

	files.each do |file_name|
    # Show progress with dots
    print "." unless details
    puts "Processing #{file_name}" if details
    file_basename =File.basename("#{file_name}", ".xml")
    file_id = 0
    # Open revised file for writing

    revised_file = File.open("#{revised_dir}/#{file_name}", "w")
    line_num = 0
    File.open("#{original_dir}/#{file_name}") do |file|
      file.each_line do |line|
      	inject_indexes = []
        if line =~ /level/
          #puts "Found: #{line}"
          inject_indexes = inject_indx(line, inject_indexes)
          puts "... processing line: #{line_num} it has indexes at: #{inject_indexes}" if details
          inject_indexes.each do |injx|
            # puts "... adding id at index: #{injx}" if details
          	file_id += 1
          	file_id_str = "umlib_#{file_basename}_#{file_id}"
          	line.insert(injx, " id=\"#{file_id_str}\" ")
          end
        end
        revised_file.puts line
        line_num += 1
      end
    end
    revised_file.close
  end
  puts
  puts "All files from #{original_dir} revised!"
end

# find all the places in line ln to inject an id
def inject_indx(ln, inject_indexes)
	search_start = 0
	found_indx = ln.index(/\slevel=/, search_start)
	return inject_indexes.reverse if found_indx.nil?

	inject_indexes << found_indx
	inject_indx(ln[(found_indx + 3)..-1], inject_indexes)
end

# puts "To run with local gems must be used in its own directory, eg, id_injector/"
# puts "To install: 'bundle install --path .bundle' in its own directory"
# puts 'Example usage: bundle exec ruby injectsomeids.rb --eads="../sctest" --eadsout="../sctest_out"'

opts = Optimist::options do
  opt :eads, "Directory with original EADs", :type => :string
  opt :eadsout, "Directory for revised EADs", :type => :string
  opt :details, "Show detailed information"
end

puts "opts are: #{opts}"

eads_revise(opts[:eads], opts[:eadsout], opts[:details])

```
