### ISSUE TITLE
User knows where they are in the hierarchy; easily discover the context of any individual item/component within the hierarchy of the collection

### ISSUE THREAD

**Issue by anarchivist** [projectblacklight/arclight#45]
* Ref: req 1.57
* Category: 1. Core Discovery
* Subcategory: UI features

**Comment by ggeisler** [comment]
In UM Bentley's ArcLight Testing report, they suggest breadcrumbs can become unwieldy when there are many levels in the hierarchy, making it more difficult for the user to understand where they are in the hierarchy:

---

<img width="727" alt="Screen Shot 2019-07-12 at 3 19 26 PM" src="https://user-images.githubusercontent.com/101482/61161585-4c72ae80-a4b9-11e9-9b1a-e372805ffe22.png">
 
---

In UAlbany's implementation, they make a fairly simple change in the breadcrumb display to stack each level of the hierarchy:

---

<img width="727" alt="Screen Shot 2019-07-12 at 3 23 03 PM" src="https://user-images.githubusercontent.com/101482/61161609-74faa880-a4b9-11e9-9528-e86a23c7f53b.png">

---

Although the latter approach uses more vertical space, I wonder if that might be sufficient to address the problem? It makes it much easier to understand the context, in my opinion.

**Comment by seanaery** [comment]
Resolving this issue as part of a review of `arclight 1.0.x`. The UI now features breadcrumbs with cascading indentation and arrows.
