### ISSUE TITLE
Collection-level online content tab displaying only 10 components

### ISSUE THREAD

**Issue by anarchivist** [projectblacklight/arclight#457]
The "Online content" tab on a collection detail page displays components with digital objects when there are no collection-level digital objects. Currently, it is displaying only 10 components. 

**Acceptance criteria (for discussion/negotiation)**

* When on the Online content tab on a collection detail page and there are no collection-level display objects, display all of the components with digital objects.
* Consider providing some pagination on this display.

**Screenshot**

![screen shot 2017-06-14 at 2 43 16 pm](https://user-images.githubusercontent.com/73732/27156117-8b74bd66-5110-11e7-80b6-23ca914de418.png)

**Comment by jrgriffiniii** [comment]
I'm still working to make progress on this.  The approach I have been taking is to add the `results_pagination` partial into https://github.com/projectblacklight/arclight/blob/master/app/views/catalog/_index_online_contents_default.html.erb (please see https://github.com/projectblacklight/blacklight/blob/master/app/views/catalog/_search_results.html.erb#L28), but this required debugging in Kaminari: https://github.com/kaminari/kaminari/blob/master/kaminari-core/lib/kaminari/helpers/helper_methods.rb#L111

**Comment by jrgriffiniii** [comment]
The approach I was taking was an erroneous one.  I have introduced JavaScript changes in https://github.com/projectblacklight/arclight/compare/master...jrgriffiniii:issues-457-jrgriffiniii-online-content-results which provides for pagination in the AJAX-loaded collection navigation element.

However, I did not have fixtures for 11 documents linking to online content, and hence I just copied spec/fixtures/ead/sul-spec/a0011.xml using different `eadid` values - is this acceptable for a pull request, or are there better fixtures which should be used?

**Comment by mejackreed** [comment]
@jrgriffiniii Feel free to push up a WIP PR with this.

Is there a way to isolate the JavaScript changes to the individual pieces that enable the pagination / more results? I also see a bit of a refactor in there and trying to determine which pieces we need.

WRT to the fixtures. I think what you have done is ok. But we could also edit the current EAD fixtures to add the additional components in which may be a bit more surgical for this feature. Happy to pair up w/ you to do that.

@anarchivist is there a real world EAD in the wild we should target for this?

**Comment by anarchivist** [comment]
Here are a couple options from Stanford:

* https://github.com/sul-dlss/stanford-arclight-test-data/blob/master/spec/m1711.xml (1.27 MB, ~500 components with digital objects, Stanford Special Collections, objects in SDR)
* https://github.com/sul-dlss/stanford-arclight-test-data/blob/master/hoover/2000C3.xml (36K, ~40 components w/ DOs, Hoover, objects not in SDR)

**Comment by mejackreed** [comment]
Full design in #679 may supersede this ticket.
