### ISSUE TITLE
Demo box: deployment fixes

### ISSUE THREAD

**Issue by anarchivist** [projectblacklight/arclight#464]
Ref #209. 

**Maintenance tasks**

* [x] Bump up box size (for memory)
* [x] Set env var to serve files #448 
* [x] Add health check (at least for `/`)
* [ ] Enable managed updates - schedule for Saturday morning 

**Separate indexing from deployment**

* [x] Remove `seed` step from EB deployment
* [x] Add step to check out or download finding aids (see #209 - last comment)
* [x] Add cron job to run indexing rake task once a day instead of on deploy
* [ ] Add documentation about how to get into EB box and run indexing/diagnose issues

**Comment by anarchivist** [comment]
Speaking with @eefahy, this is done except for enabling managed updates and writing up docs. Managed updates should be turned on after the demo on July 14th, and Erin and I will have a meeting to talk through the documentation needs (and maybe just to write up the docs together).

**Comment by seanaery** [comment]
Resolving this issue as part of a review of arclight 1.0.x. Any remaining issues with the arclight-demo application should be reported/tracked at https://github.com/sul-dlss/arclight-demo
