### ISSUE TITLE
Indexer/solr_ead behavior and root Solr document size

### ISSUE THREAD

**Issue by anarchivist** [projectblacklight/arclight#473]
In trying to index one of the Stanford Archive of Recorded Sound finding aids ([ARS.0043](https://github.com/sul-dlss/arclight-demo/blob/master/data/ead/sul-ars/ARS.0043_ead.xml)), I noticed that the demo site's Solr instance was throwing a 413 error (Request Entity Too Large) when it was indexing.

In the case of this finding aid, there are `<persname/>`s and other controlled access terms at many component levels throughout the finding aid. `solr_ead`'s underlying indexer behavior is creating many `persname_sim`, etc. fields for the root-level document. We should probably look to see if we can override this in some way.

**Comment by mejackreed** [comment]
I've resolved this manually in the Blacklight EBS solr 8 instance. Needed to manually update the nginx config to enable a larger max body size:

```
http {
...
    # set client body size to 30M
    client_max_body_size 30M;
}
```
