### ISSUE TITLE
BS4: compact vs list view highlighting needs better contrast to determine active state

### ISSUE THREAD

**Issue by anarchivist** [projectblacklight/arclight#478]
The difference between active and inactive in BS4 buttons is very subtle, and is somewhat confusing.

![fvhowtwmiv](https://user-images.githubusercontent.com/73732/30835844-59f817c4-a20f-11e7-9eca-4086528d7a98.gif)

**Comment by anarchivist** [comment]
Will be closed by projectblacklight/blacklight#1788

**Comment by ggeisler** [comment]
Agreed. And I'm also not a fan of the colors themselves; they're kind of dark and more dominant than ideal for non-primary buttons.

I wonder if we might try `btn-outline-secondary` instead? Though I believe they both fail AA contrast requirements so if we want to do the right thing for accessibility we're going to have to override the BS defaults anyway.

**Comment by anarchivist** [comment]
I think using `.btn-outline-secondary` is @mejackreed's PR projectblacklight/blacklight#1788.

**Comment by ggeisler** [comment]
Okay, great. I didn't see the reference until after posting my comment...

**Comment by anarchivist** [comment]
Yeah, I forgot that there was a PR in for this already until I did a little digging.

**Comment by mejackreed** [comment]
Resolved upstream and with Blacklight 7
