### ISSUE TITLE
When > 100 collections are indexed, the "Collections" page reads "100 collections"

### ISSUE THREAD

**Issue by anarchivist** [projectblacklight/arclight#487]
<img width="1037" alt="screen shot 2018-07-23 at 11 18 43 pm" src="https://user-images.githubusercontent.com/73732/43114837-ee593856-8ece-11e8-8f3b-07d1492bb5a0.png">

**Comment by anarchivist** [comment]
This view uses `ArclightHelper#collection_count`, as far as I can tell - and doesn't use the same method/query that the Repositories index page does.

**Comment by christinach** [comment]
This was fixed https://github.com/projectblacklight/arclight/pull/490/commits/4e9bac66b7996aefddf278e739d16e53f6cca9d4

**Comment by mejackreed** [comment]
Thanks @christinach
