### ISSUE TITLE
Certain EAD level components lead to a confusing display

### ISSUE THREAD

**Issue by anarchivist** [projectblacklight/arclight#493]
The `level` attribute on `<c/>` or `<cXX/>`can have certain values, like `recordgrp`, `subgrp`, `class`, and `otherlevel`. I believe we map `otherlevel` appropriately, but the rest lead to issues as indicated in the screenshots.

![screen shot 2018-11-07 at 10 58 02 am](https://user-images.githubusercontent.com/73732/48153839-0a370480-e27c-11e8-83b8-7d1a7cde9fed.png)
![screen shot 2018-11-07 at 10 53 08 am](https://user-images.githubusercontent.com/73732/48153841-0c00c800-e27c-11e8-9ed3-1f89e9765e53.png)

**Comment by seanaery** [comment]
Resolving this issue as part of a review of `arclight 1.0.x`. This issue is no longer present in the UI in v1.
