### ISSUE TITLE
Component displays all child access restrictions.

### ISSUE THREAD

**Issue by gwiedeman** [projectblacklight/arclight#498]
Lower level access restriction notes will each show up in a parent’s “Terms & Conditions” card. Thus, if a series does not have an access note, but some of its children do, it will display the restrictions of all its children, potentially a lot of them.

This is an indexing issue, and fixing it potentially creates a design issue. Child access restrictions are added to a components accessrestrict_ssm field. This [fix to solr_ead_indexer_ext.rb](https://github.com/UAlbanyArchives/arclight-UAlbany/commit/f66382b7f6b7f1ef1793d7377317b330385ae2c8#diff-ab385a02a8028462403d51dff1f3d568) fixes that.

However, this potentially creates a design issue, as a child note should override its parent, but if a parent has a note that states that its unrestricted, it still shows up in the “Terms & Conditions” card for lower lever components that have an overriding access restriction note.

**Comment by mejackreed** [comment]
We want to make sure that doesn't happen in the new traject based indexer.

**Comment by jrgriffiniii** [comment]
Is this field now being indexed using`parent_access_restrict_ssm` in https://github.com/projectblacklight/arclight/blob/master/spec/features/traject/ead2_indexing_spec.rb#L331?

**Comment by seanaery** [comment]
Hi @jrgriffiniii --

> Is this field now being indexed using `parent_access_restrict_ssm`

This issue @gwiedeman logged is now fixed with our shift to Traject. That is, a component no longer displays any of its descendants' restrictions.

There are related issues going the other way -- components inheriting restrictions from ancestors -- that `parent_access_restrict_ssm` addresses. I created issue #784 to map out all of our fields that currently have inheritance and invite feedback on what adjustments we still need to make with respect to metadata being inherited from ancestors or descendants.

**Comment by seanaery** [comment]
One particular related issue on #784 that needs exploration/resolution is whether there really needs to be a separate "restrictions" vs. "parent restrictions" distinction on a component (our current state). To @gwiedeman 's point, it could be confusing if a restricted component simultaneously showed its restrictions AND the unrestricted statement from its parent.

We could easily just use one "restrictions" field in the indexing process: the component could get its value from its own `<accessrestrict>` if present, or if not, whatever nearest ancestor has an `<accessrestrict>` (including top-level).

**Comment by seanaery** [comment]
I have labeled this one as Blocked (by #784).

**Comment by seanaery** [comment]
Resolving this issue as part of a review of arclight 1.0.x. There are still inheritance issues to sort out (per #784) but the specific bug reported here where child restrictions were appearing on component pages is no longer happening.
