### ISSUE TITLE
Component Parents of components with online content do not show that they have online content within them

### ISSUE THREAD

**Issue by gwiedeman** [projectblacklight/arclight#506]
While the collection-level view will show online content if there is any `<dao href="">` in the entire collection, components with `<dao href="">` tags at lower levels do not display as showing online content.

![image](https://user-images.githubusercontent.com/10030353/53916768-fb493e80-4030-11e9-8d6c-076ec5234169.png)

This is primarily an indexing issue. 

![image](https://user-images.githubusercontent.com/10030353/53916973-77dc1d00-4031-11e9-8eab-7873b84d1c83.png)

The XPath in `shared_indexing_behavior.rb` is correct, but it looks like methods in that file only have access to the XML of that component, and not any children, so it returns false. This is not the case for the collection-level, which works as expected.

https://github.com/sul-dlss/arclight/blob/3af789cb19e18a9000ee6d0912ef899df961f0b6/lib/arclight/shared_indexing_behavior.rb#L93-L95

My hacky solution was to move the online_content? method from `shared_indexing_behavior.rb`  to `solr_ead_indexer_ext.rb`: 

https://github.com/UAlbanyArchives/arclight-UAlbany/blob/9ab258115b656b7944eba1bf08505e227fc8c824/lib/arclight/solr_ead_indexer_ext.rb#L167-L170

and call it here:

https://github.com/UAlbanyArchives/arclight-UAlbany/blob/9ab258115b656b7944eba1bf08505e227fc8c824/lib/arclight/solr_ead_indexer_ext.rb#L19

This does not override the original method for some reason unbeknownst to me, even removing these lines:

https://github.com/sul-dlss/arclight/blob/3af789cb19e18a9000ee6d0912ef899df961f0b6/lib/arclight/custom_component.rb#L58
https://github.com/sul-dlss/arclight/blob/3af789cb19e18a9000ee6d0912ef899df961f0b6/lib/arclight/custom_document.rb#L65

Also, the new method in `solr_ead_indexer_ext.rb` does not get called at the collection-level, so my really hacky temporary fix was to re-enable the original method when `self.ng_xml.root.name == "ead"` ¯\_(ツ)_/¯:

https://github.com/UAlbanyArchives/arclight-UAlbany/blob/4402924d430708c34c88de889dc161aec1255edf/lib/arclight/shared_indexing_behavior.rb#L93-L98
![image](https://user-images.githubusercontent.com/10030353/53916838-2d5aa080-4031-11e9-9dfa-f55bd5928bc4.png)

Once it indexes correctly, there is still a display issue, as the existing online content display shows all online content in the collection, not just from children of that component:

https://github.com/sul-dlss/arclight/blob/a1ec06251b5a937e785d32ef74f2adb817df5ae6/app/views/catalog/_collection_online_contents.html.erb#L7-L13

My fix is here, but there's probably a cleaner way:

https://github.com/UAlbanyArchives/arclight-UAlbany/blob/6a24ea89e9045d0822731008d5c2663d08876217/app/views/catalog/_daos.html.erb#L72-L101

**Comment by seanaery** [comment]
Resolving this issue as part of a review of `arclight 1.0.x`.  A component does now show as having online content if it doesn't have its own `<dao>` but one of its child components does.
