### ISSUE TITLE
Possible bug with index rake command - runs indexing more than once

### ISSUE THREAD

**Issue by gordonleacock** [projectblacklight/arclight#507]
Example:
```[gordonl@nectar current]$ SOLR_URL=http://localhost:8082/solr/arclight_testing RAILS_ENV=production FILE=./eads/clemdata_revised/C2/hollowayj_final.xml REPOSITORY_ID=umich-wlcl bundle exec rake arclight:index```
```Loading ./eads/clemdata_revised/C2/hollowayj_final.xml into index...
Indexed ./eads/clemdata_revised/C2/hollowayj_final.xml (in 50.644 secs).
Loading ./eads/clemdata_revised/C2/hollowayj_final.xml into index...
Indexed ./eads/clemdata_revised/C2/hollowayj_final.xml (in 46.96 secs).
Loading ./eads/clemdata_revised/C2/hollowayj_final.xml into index...
Indexed ./eads/clemdata_revised/C2/hollowayj_final.xml (in 50.208 secs).
[gordonl@nectar current]$```

**Comment by mejackreed** [comment]
Acceptance criteria:
 - [ ] determine if this is still an issue
 - [ ] see if this is an issue with new traject approach (if not, 🆗 to close)

**Comment by gordonleacock** [comment]
Okay, I don't think this is an issue, so I'm closing it.
