### ISSUE TITLE
Verify bug: Selecting label in facet headers seems broken

### ISSUE THREAD

**Issue by ggeisler** [projectblacklight/arclight#508]
When trying to open the facet boxes from a search results page, things work as expected when you open the facet box with the disclosure icon or clicking on the header. But if you click, or use the keyboard to select, the label in the facet header, the facet box opens and then immediately closes. In the gif below, I am only clicking on each label once:

![arclight-facet-problem](https://user-images.githubusercontent.com/101482/61481314-d9e84f80-a94c-11e9-9683-9838edcd3e0c.gif)

In case it helps troubleshooting the issue, in UAlbany's instance there is a similar issue, though in that case the facet box stays open but causes the page to scroll (but if you use the disclosure icon, it works as expected).

**Comment by mejackreed** [comment]
I think this may be fixed upstream in https://github.com/projectblacklight/blacklight/pull/2113 but we may need a new Blacklight release to get it.

**Comment by camillevilla** [comment]
I believe this was resolved by https://github.com/projectblacklight/blacklight/releases/tag/v7.1.0, so the action item here is verify whether this bug is still active.

**Comment by labradford** [comment]
I was just looking at this and it looks fixed to me on the arclight demo site. I can add a video demo to this.

**Comment by labradford** [comment]
<video src="https://d2ddoduugvun08.cloudfront.net/items/1p3Q0y3f293m0h263i0q/Screen%20Recording%202019-09-17%20at%2004.23%20PM.mov" controls style="display: block;height: auto;width: 100%;">Screen Recording 2019-09-17 at 04.23 PM.mov</video>
