### ISSUE TITLE
Receive clear and unambiguous information regarding applicable use or access restrictions that could impact his requests.

### ISSUE THREAD

**Issue by anarchivist** [projectblacklight/arclight#51]
* Ref: req 2.23
* Category: 2. User/Request Management
* Subcategory: UI Features

**Comment by seanaery** [comment]
Resolving this issue as part of a review of `arclight 1.0.x`. Access restrictions in v1 are displayed directly on a component show page e.g., https://arclight-demo.projectblacklight.org/catalog/pc0170-xmlaspace_6a6648be46e57d220d1f4f6d07316570
