### ISSUE TITLE
Split breadcrumbs into new lines

### ISSUE THREAD

**Issue by ggeisler** [projectblacklight/arclight#512]
- [ ] Display each breadcrumb on a new line

- [ ] Indent each new line `10px` (should look roughly similar to the UAlbany screenshot below)

Because components can have long titles and can be deep in a hierarchy, using the traditional approach of showing breadcrumbs in a single line can creating breadcrumb groups that are difficult to parse:

<img width="917" alt="Screen Shot 2019-07-18 at 11 45 34 AM" src="https://user-images.githubusercontent.com/101482/61483563-eb802600-a951-11e9-9f0d-ab295fd7bf11.png">

---

Displaying each breadcrumb on a new, indented line works makes parsing the hierarchy much easier:

<img width="493" alt="Screen Shot 2019-07-18 at 11 46 32 AM" src="https://user-images.githubusercontent.com/101482/61483608-08b4f480-a952-11e9-8403-05f0d376a4e2.png">

**Comment by jvine** [comment]
Just to clarify:  this ticket is only about about displaying each link on a new line with an indent. 

Per post-standup discussion: we do not want a more/less link for long hierarchies.

Any column layout changes that affect the hierarchy will be handled in a separate ticket.

**Comment by jvine** [comment]
Looking at accessibility for this in both the hierarchy view (component page) and flat list (search results). I think the best solution is to use a `<ul>` structure, like this:

```
<ul aria-label="Collection breadcrumb">
 <li>link</li>
 <li>link</li>
</ul>
```

Screen reader will read the label and announce the number of links.

- aria-label needs to be translatable
- The list can be styled flat with `display:inline` where necessary (e.g. search results).
- Some magic needs to apply incremental indents in the hierarchy view. 
- The indents need to be suppressible in mobile/small displays, where all items will be flush-left.
- Any special characters like `»` should be in CSS only. (Note that in the component page, there will be icons that precede each level. This will likely not carry to the search results.)

(The parent/child thing I was looking for was unrelated.)

**Comment by mejackreed** [comment]
@jvine I dropped a quick PR about styling around that type of markup here: https://github.com/projectblacklight/arclight/pull/615/files

**Comment by seanaery** [comment]
^ @mejackreed Clever use of scss there... I like it.

**Comment by jvine** [comment]
^ Me too.
