### ISSUE TITLE
Add sort and layout options to "Online" view

### ISSUE THREAD

**Issue by ggeisler** [projectblacklight/arclight#514]
The display of items in the "Online" view is roughly equivalent to displaying search result items in any Blacklight-based app, where there are typically options for the user to change sort order and layout. We should think about whether these options make sense for the "Online" view and if so, provide design direction for implementing.

**Comment by seanaery** [comment]
Resolving this issue as part of a review of `arclight 1.0.x`. The "Online" view _is_ now an index view with facets and search result sort & per-page widgets.
