### ISSUE TITLE
Improve display of component page elements

### ISSUE THREAD

**Issue by ggeisler** [projectblacklight/arclight#519]
Making sense of all the elements shown on a component detail page is currently more difficult than it should be. We need to rethink the layout of this page and how we group and label things:

<img width="963" alt="Screen Shot 2019-07-19 at 2 10 22 PM" src="https://user-images.githubusercontent.com/101482/61566024-b0542480-aa2f-11e9-81eb-fcb3ac08b895.png">

---

Improved design TBD.

**Comment by anarchivist** [comment]
Closed by #632
