### ISSUE TITLE
Improve styling of tabs on component page

### ISSUE THREAD

**Issue by ggeisler** [projectblacklight/arclight#520]
Probably related to #519.

Although we want to keep the base application pretty generic and not impose design opinions on implementers, we might want to consider improving how we display the Overview, Contents, and Online content tabs on the component page. Feedback suggests users might not read these as tabs or different views of the content. UAlbany's customization is [one potential approach](https://archives.albany.edu/collections/catalog/ua200aspace_6ba366b1d54ded6ce6aa47463ba7883d) that improves things.

**Comment by anarchivist** [comment]
Closed by #645/#632
