### ISSUE TITLE
Rewrite indexing tooling

### ISSUE THREAD

**Issue by anarchivist** [projectblacklight/arclight#528]
Indexing currently depends on `solr_ead` and `solrizer`, the latter of which is advancing towards being deprecated (see [here](https://samvera.github.io/deprecation.html#deprecation-process-from-core)). From Stanford's perspective, Traject is a likely candidate to replace this. 

Feedback from estimation:
* High priority
* should be done at the beginning of the work cycle

**Comment by escowles** [comment]
`solr_ead` also depends on `om`, which is also on track to be deprecated. So having this as a high priority sounds good to me.

**Comment by escowles** [comment]
See proposal to deprecate `om`: https://groups.google.com/d/msg/samvera-tech/2Ul7fumgJbA/6e87E3WxEQAJ

**Comment by awead** [comment]
Chiming in from the peanut gallery: traject could replace om in solr_ead, so you could still use the solr_ead gem to index and break apart ead into smaller bits. That is, if you still want to maintain solr_ead as a separate dependency. For the record, I'm totally ok if you want to ditch solr_ead altogether. I'm just curious if its features are still worthy of a separate gem.
