### ISSUE TITLE
Better integrate online content into component pages

### ISSUE THREAD

**Issue by anarchivist** [projectblacklight/arclight#536]
Currently online content is displayed on its own tab; this obscures it from many users. This in part is a proposal to move this to the main tab. 

More broadly: how can we make online content more functional, discoverable, easy to access?

(Comments re: generic viewer integration moved to #60)

**Comment by anarchivist** [comment]
Separate tab-related concern from need to incorporate viewers

**Comment by eckardm** [comment]
Hi Gary and Mark. These look great! I definitely think these would make online content less obscure and make it more more functional, discoverable, and easy to access.

I had a couple thoughts on the file-level component when all we have is an external link to online content. I think we'd end up with a fair bit of these, with content linking out to DSpace, Archive-IT, etc., even though we'd also have some digitized collections where we could use the viewer too.

The link to the content looks a lot like other hyperlinks on the page (e.g., to other components of archival description in ArcLight). Some different styling or information or an icon that tells you about what it is (or even a `fa fa-external-link` icon) might help to draw attention to the fact that not only is this a different type of link, it would take you outside ArcLight. I think the thumbnail examples really make it this clear, so it would be like that, but more generic.

**Comment by ggeisler** [comment]
> Some different styling or information or an icon that tells you about what it is (or even a fa fa-external-link icon) might help to draw attention to the fact that not only is this a different type of link, it would take you outside ArcLight.

Nice idea @eckardm, we'll definitely try to work something like that in as we move forward with the online content section of the file-level component page. Thanks!

**Comment by anarchivist** [comment]
Closed because #678 is better broken down
