### ISSUE TITLE
Long facet lists should provide a modal window

### ISSUE THREAD

**Issue by anarchivist** [projectblacklight/arclight#537]
Currently, the long facet lists are not easy to use; instead, we should provide the option for a modal that presents the expanded list of all facets.

**Comment by ggeisler** [comment]
Just noting that I think the most obvious solution to this is pretty clear: [using the "Limit" option in Blacklight](http://jessiekeck.com/customizing-blacklight/facets/) so a long facet list becomes a shorter facet list with a "more" link that opens a modal:

![Screen Shot 2019-07-23 at 9 26 41 AM](https://user-images.githubusercontent.com/101482/61729752-c3ffd380-ad2c-11e9-855b-e38a8038bcfe.png)

I'd suggest using `10` as the limit value. 

If by chance this doesn't seem like the right solution to anyone I suggest adding a design needed label to this issue with an explanation of why the above solution isn't ideal for ArcLight.

**Comment by jrgriffiniii** [comment]
https://github.com/projectblacklight/arclight/compare/master...jrgriffiniii:issues-537-jrgriffiniii-facet-modal?expand=1 sets the limit explicitly to `10` for field facets.  Is the default modal acceptable for a PR, should any style properties be overridden?  Please see:

![image](https://user-images.githubusercontent.com/1443986/63026392-1b4f1a80-be79-11e9-8b0b-842802faa11f.png)

**Comment by ggeisler** [comment]
@jrgriffiniii No, I think we should just stick with the basic styling we inherit from Blacklight, at least for now. Thanks for checking!
