### ISSUE TITLE
Expand configuration for repositories to allow for additional fields

### ISSUE THREAD

**Issue by anarchivist** [projectblacklight/arclight#541]
Proposed by IU: (i.e., unit’s home URL) - also rename YAML fields so they are more generic (i.e., google_request_url) Can we use ArchivesSpace info to populate YAML file?

**Comment by camillevilla** [comment]
@anarchivist will follow up re: desired ArchivesSpace info. For now, we'll be focusing on implementing and documenting #592

**Comment by anarchivist** [comment]
@jlhardes Can you clarify what IU is looking for here:

>  Can we use ArchivesSpace info to populate YAML file?

**Comment by jlhardes** [comment]
We're wondering here how ArcLight is indexing from ArchivesSpace. Is that done directly from the ASpace database or only via EAD XML exports? We have a particular concern that the repository home URL can show in ArcLight and we're not sure if the EAD export includes that or if ArcLight has the capacity to show that. The repository information is managed in ASpace in a different spot from Resources (finding aids) so it's possible that information we'd want to include about the repository in ArcLight is not part of what is exported via EAD. If ArcLight isn't pulling info directly from ASpace, is it possible to do that for repository info? If not, we'll either need to work with the repo info that ASpace includes in the EAD XML or manage that with local changes. Does that help?

**Comment by noahgh221** [comment]
Generally, we (Duke) like the YAML method for supplying repository information. It gives us flexibility to present/describe repositories (or other administrative units or collecting areas) separately that might not be managed separately in ASpace or might not be represented separately in EAD metadata. It also seems much simpler than relying on ASpace data or EAD data. I don't have suggestions for any additional fields to add, but having flexibility to add fields is desirable.

**Comment by anarchivist** [comment]
@jlhardes 💬 

> We're wondering here how ArcLight is indexing from ArchivesSpace. Is that done directly from the ASpace database or only via EAD XML exports? 

At this point it's only done by EAD XML exports. Lyrasis created an [ArcLight indexer](https://github.com/lyrasis/arclight-oai-indexer) to pull from ArchivesSpace's OAI endpoint. It was a potential early goal to pull from the ArchivesSpace API but we haven't done any integration work there yet, nor have we prioritized it (yet) for this work cycle. 

> We have a particular concern that the repository home URL can show in ArcLight and we're not sure if the EAD export includes that or if ArcLight has the capacity to show that. The repository information is managed in ASpace in a different spot from Resources (finding aids) so it's possible that information we'd want to include about the repository in ArcLight is not part of what is exported via EAD. If ArcLight isn't pulling info directly from ASpace, is it possible to do that for repository info? If

I'm not sure about the EAD export, but #591 and #592 should address adding that information. There are some design changes that will be necessary to figure out how to integrate that. 

Let me know if this answers your questions.

**Comment by jlhardes** [comment]
Thanks @anarchivist - that answers my questions and #591 and #592 look great from IU's perspective!
