### ISSUE TITLE
Persistent hierarchical component navigation

### ISSUE THREAD

**Issue by anarchivist** [projectblacklight/arclight#546]
Persistently display on component views a navigable hierarchy of the collection (w/current location highlighted). E.g., ASpace PUI & Princeton's UI. 

Relates to #534 but a bit different. See also #45 and #44.

**Comment by anarchivist** [comment]
see #246 for an alternate design from the MVP

**Comment by seanaery** [comment]
Resolving this issue as part of a review of `arclight 1.0.x`. This was implemented in v1.
