### ISSUE TITLE
Support for user access to digital content

### ISSUE THREAD

**Issue by anarchivist** [projectblacklight/arclight#55]
* Ref: req 6.13
* Category: 6. Digital objects
* Subcategory: Integrated delivery

**Comment by seanaery** [comment]
Resolving this issue as part of a review of `arclight 1.0.x`. This is generally supported in v1 as basic `<dao>`s render as links to digital content; collections/components that have digital content are distinguished and facetable in the UI; and basic `oembed` support is in place. More specific features for digital content should be documented as individual issues.
