### ISSUE TITLE
Document currently used solr fields in ArcLight

### ISSUE THREAD

**Issue by mejackreed** [projectblacklight/arclight#557]
Split out of #528 a prerequisite as we define new indexing Intermediate Representation (IR).

SolrEad Document Indexer: https://github.com/awead/solr_ead/blob/54a5f5217152882946be6d4ee6deda0e1c80263c/lib/solr_ead/document.rb

SolrEad Component: 
https://github.com/awead/solr_ead/blob/54a5f5217152882946be6d4ee6deda0e1c80263c/lib/solr_ead/component.rb

Where "index_as" is stored: https://github.com/samvera-deprecated/solrizer/blob/master/lib/solrizer/default_descriptors.rb

**Comment by mejackreed** [comment]
Part of #529

**Comment by estelendur** [comment]
[Here is what I've documented so far](https://docs.google.com/spreadsheets/d/1fyexaBGviAiR09YJ3sWHvWSjRjOWOfGdXe9Z7PeoqH8/edit?usp=sharing). This covers the terminology for `SolrEad::Document` and `SolrEad::Component`.

I've been looking at `Arclight::SolrEadIndexerExt` and it's somewhat more complex, in that we are normalizing and reconstructing some fields. I'm not sure what the best way to document those fields is - just list their names? Or something more in-depth?

**Comment by mejackreed** [comment]
Thanks so much @estelendur. I think just listing their name seems sufficient. We can do more in depth analysis as we move forward on an implementation path.

**Comment by estelendur** [comment]
Alright, I've added the solr_names of the fields to a third tab in the Google Sheet.
