### ISSUE TITLE
Remove namespaces requirement from EAD traject indexing

### ISSUE THREAD

**Issue by mejackreed** [projectblacklight/arclight#575]
@anarchivist mentioned in standup that valid EAD2002 may not contain namespaces. Can we account for this in our traject indexing approach

**Comment by mejackreed** [comment]
solr_ead just `remove_namespaces!` should we do something different /similar? What are the implications for traject? https://github.com/awead/solr_ead/blob/54a5f5217152882946be6d4ee6deda0e1c80263c/lib/solr_ead/behaviors.rb#L14

**Comment by billdueber** [comment]
Some thoughts. What are the odds that an EAD will have 
* correctly namespaced nodes, and then valid non-namespaced nodes used for another purpose?
* A mix of correctly-namespaced and bare tags, the latter of which should be namespaced but for whatever reason aren't? 

If the answer for the first is (as I suspect) "close enough to zero to not bother" then stripping the namespaces is probably ok. I think we even see a performance boost :-)

**Comment by jrgriffiniii** [comment]
`options` in https://github.com/sparklemotion/nokogiri/blob/master/lib/nokogiri/xml/document.rb#L47 is yielded to `config_proc` in https://github.com/traject/traject/blob/master/lib/traject/nokogiri_reader.rb#L97, but I'm not certain how one strips namespaces given what options I'm finding in https://github.com/sparklemotion/nokogiri/blob/master/lib/nokogiri/xml/parse_options.rb

**Comment by jrgriffiniii** [comment]
`solr_ead` uses `remove_namespaces!` in https://github.com/awead/solr_ead/blob/master/lib/solr_ead/behaviors.rb#L14, so perhaps it should be invoked in an `extra_xpath_hook` here: https://github.com/traject/traject/blob/master/lib/traject/nokogiri_reader.rb#L118

**Comment by jrgriffiniii** [comment]
https://github.com/projectblacklight/arclight/compare/master...jrgriffiniii:issues-575-jrgriffiniii-remove-ead-namespaces removes the namespaces, but I doubt that it's the best approach (apologies).

I can proceed with copying a EAD2002 fixture and stripping its namespaces.

**Comment by jrgriffiniii** [comment]
https://github.com/traject/traject/blob/master/lib/traject/macros/nokogiri_macros.rb#L21 seems to be blocking me from proceeding (perhaps stripping the XML namespaces prevents this `lambda` from being invoked)

**Comment by anarchivist** [comment]
So, mulling on this a bit, I suspect the namespace issues I was afraid relate to EAD 1.0 and EAD 2002 and the use of XLink. For DTD-compliant EAD of both versions I think there were complicated workarounds to deal with this. Schema-compliant EAD just uses XLink attributes with the correct namespace; DTD has a weird "opt-in" aspect.

**Comment by jrgriffiniii** [comment]
https://github.com/traject/traject/blob/master/lib/traject/indexer.rb#L523 is where the `Nokogiri::XML::Document` is constructed during parsing, but I still cannot find any means by which to ensure that this is consistently stripped of namespaces using the approach in: https://github.com/projectblacklight/arclight/compare/master...jrgriffiniii:issues-575-jrgriffiniii-remove-ead-namespaces

I'm going to see about trying to address this from within the structure of the XPaths.

**Comment by jrgriffiniii** [comment]
https://github.com/projectblacklight/arclight/commit/4395d044097e08f4c3979c90ada953280177dcb5 seems to get this working, I will need to refactor this approach.
