### ISSUE TITLE
Provide by browse by subject/creator

### ISSUE THREAD

**Issue by anarchivist** [projectblacklight/arclight#6]
* Ref: req 1.12
* Category: 1. Core Discovery
* Subcategory: Browse

**Comment by ggeisler** [comment]
@anarchivist Can you say more about this, or point me to the AS PUI report? 

In the requirements spreadsheet, the requirement 1.12 indicates it comes just from the "ArchivesSpace PUI Report". If this means the U. of Illinois report, I can't find where the requirement comes from ("browse" appears only once in that document, and not in the context of "subject/creator"). Or is the reference to some other report?

**Comment by anarchivist** [comment]
I believe that's this report: http://cherryhill.github.io/aspace_pui/ArchivesSpacePUI_report_20151221.pdf (see page 4).

**Comment by ggeisler** [comment]
Okay, got it, thanks.

**Comment by seanaery** [comment]
Resolving this issue as part of a review of `arclight 1.0.x`. Creator and Subject are captured as facets. Implementers wishing to link to a browsable list of facet values (sorted alphabetically or by frequencey) may do so at, e.g.,:
https://arclight-demo.projectblacklight.org/catalog/facet/creator?facet.sort=index&q=&search_field=all_fields
https://arclight-demo.projectblacklight.org/catalog/facet/subject?facet.sort=index&q=&search_field=all_fields
