### ISSUE TITLE
Integrating with systems that deliver digital content outside of ArcLight

### ISSUE THREAD

**Issue by anarchivist** [projectblacklight/arclight#60]
* Ref: req 5.9
* Category: 5. System integration/data export
* Subcategory: Digital object delivery

**Comment by anarchivist** [comment]
How can we make easily integrate digital object viewers more functional, discoverable, easy to access?

Additional feedback from estimation process:

* IU - would like ability to embed any multimedia viewer (Universal Viewer, Avalon Player, PDF viewers, etc.) to handle analog and born-digital captures of files.
* UM - From Bentley document:
  * Embedding and display of digital content from various platforms directly on the pages of archival components
  * digital content should be presented more directly to users (as opposed to requiring additional clicks to access)
  * users should be able to acquire persistent URLs to pages in ArcLight that display digital content.
* UA: might be a broader conversation, but probably a step in the right direction. Would be great to pull in Hyrax objects more usably then we currently do
* DUKE: We need the digital object "use statement" (mapped to dao@role in EAD) indexed so we can distinguish e.g., video from image objects to load the corresponding viewer tool inline. **(indexing issue)**
* Stanford uses oEmbed for SDR content

**Comment by anarchivist** [comment]
See also #57, #62

**Comment by mejackreed** [comment]
Closed in favor of #906
