### ISSUE TITLE
Add the Access tab, move content from the sidebar

### ISSUE THREAD

**Issue by jvine** [projectblacklight/arclight#633]
Part of #632 

- [ ] Add an Access tab as the last item in the tab list. 

### Tab content

Add tab content in the following order. Content is arranged in the standard `<dl>` structure with exceptions noted.

**Collection overview page**
- [ ] RESTRICTIONS
   - from the "Terms & Conditions" accordion section

**Component pages**
- [ ] RESTRICTIONS
   - **component-level restrictions**, if any
   - `<dd>` value is highlighted with a background colour (start with "info" colour; may change)
- [ ] PARENT RESTRICTIONS
   - from the "Terms & Conditions" accordion section
   - restrictions inherited from the parents of this component

**All pages**
- [ ] TERMS OF ACCESS
   - from the "Terms & Conditions" accordion section
- [ ] PREFERRED CITATION
   - from the "How to cite this collection" accordion section
- [ ] LOCATION OF THIS COLLECTION
   - from the "In person" accordion section
   - display the repository image, with the repository address aligned beside it
   - image has a max-width and max-height of 150px
   - repository name is linked to the Arclight repository page
- [ ] BEFORE YOU VISIT
   - from the "In person" accordion section
- [ ] CONTACT 
   - repository phone and email from the "In person" accordion section

### Collection overview
<img width="989" alt="Access collection" src="https://user-images.githubusercontent.com/6945691/63720880-ee015580-c804-11e9-9e76-7861105ec3d4.png">

### Component page

The alert badge on the Access tab will be ticketed separately. 

<img width="993" alt="Access component" src="https://user-images.githubusercontent.com/6945691/63720886-f2c60980-c804-11e9-9dbd-ea82dc9e66c3.png">

**Comment by labradford** [comment]
Closed with PR https://github.com/projectblacklight/arclight/pull/684
