### ISSUE TITLE
Ensure component title wraps appropriately

### ISSUE THREAD

**Issue by ggeisler** [projectblacklight/arclight#637]
Part of #629 / #628.

I'm not sure how much, if any, work this will require, but after issues #630 and #631 have been completed, we should ensure that the component title wraps as necessary while maintaining the desired vertical placement below the last breadcrumb node.

Here's what I mean: 

Ideally we'd like the component title to extend full-width of the page (to the right) whenever possible, such as this:

<img width="1146" alt="Screen Shot 2019-08-26 at 2 54 18 PM" src="https://user-images.githubusercontent.com/101482/63726294-bb118e80-c811-11e9-854e-5a93f8d8b551.png">

However, the priority is that the title fit into the breadcrumb hierarchy (visually) with no unusual vertical gap between the final node of the breadcrumbs and the title. In some cases, this means that a long title will not be able to extend full-width because it will be in the same horizontal space as the component context/actions box described in #631. For example, if the previous example was one level higher in the hierarchy, extending the title all the way to the right would conflict with the context/actions box:

<img width="986" alt="Screen Shot 2019-08-26 at 3 19 04 PM" src="https://user-images.githubusercontent.com/101482/63727386-ffeaf480-c814-11e9-8907-1a49ec94b8a3.png">

Rather than create a vertical gap above the title that would enable the title to extend full-width below the context/actions box, we'd prefer that it wraps at the box like this:

<img width="986" alt="Screen Shot 2019-08-26 at 2 56 02 PM" src="https://user-images.githubusercontent.com/101482/63726419-10e63680-c812-11e9-9079-2dd5322a3936.png">

So:

- [ ] Component title extends full-width of the page if there is no conflict with the context/actions box

- [ ] Component title wraps at the context/actions box if it would otherwise need to move down vertically to avoid overlapping with the context/actions box.

**Comment by gordonleacock** [comment]
@ggeisler Hi Gary, the way we display the action box in PR##695 (still not completed) is by placing the breadcrumb in a col-md-9 div and the action box in col-md-3 div, so there is no overlap. This design is only for the components show page not the collections show page.

**Comment by gordonleacock** [comment]
@ggeisler Open to meeting this requirement differently if col-md-9/col-md-3 solutions isn't adequate but would need styling guidance on show best to do that.

**Comment by ggeisler** [comment]
@gordonleacock I think it is too soon to say whether this is closeable. I need to see the actions box in action, with the changes in other PRs related to the action box merged, before we can judge how well the component title wrapping works.

So let's keep this open and I'll comment back here when I can test things at a more complete state.

**Comment by ggeisler** [comment]
Okay, now that we have the actions box resizing correctly, it's pretty clear that the goal of this ticket has not yet been met:

>Component title extends full-width of the page if there is no conflict with the context/actions box

Example:

<img width="997" alt="Screen Shot 2019-09-18 at 2 18 55 PM" src="https://user-images.githubusercontent.com/101482/65186810-49e38680-da1f-11e9-96f9-378085e76708.png">

---

This is definitely not our highest-priority issue right now, and it might take some advanced effort to figure out (I'm not 100% sure how feasible it is, I'm just hopeful that using something like flexbox to hold both the breadcrumbs and the actions box, rather than separating them into `col-9  | col-3`, might be a solution), so feel free to unassign yourself @gordonleacock so you can focus on other things, and we can revisit this after our higher-priority issues have been dealt with.

**Comment by mejackreed** [comment]
@gordonleacock unassigning you here so we can move this to Ready.

**Comment by ggeisler** [comment]
It sounds like the title wrapping behavior I described as a goal in the original description of this ticket might be difficult to accomplish, especially if we want to maintain a decent presentation of the breadcrumb/actions box area on mobile. 

If that's the case, I'd suggest we just live with the current behavior of the component title/actions box (at least for now). But it would be nice to update the actions box itself so that it is variable width. That is, we often have cases like this:

<img width="328" alt="Screen Shot 2019-10-01 at 12 35 50 PM" src="https://user-images.githubusercontent.com/101482/66007000-82df1a80-e465-11e9-91c4-471450474faa.png">

where there is a lot of empty space on the right-side of the box. It would be better if we could make the width of the actions box variable so that it just fits the content and the outer padding. So the example above would look more like this:

<img width="226" alt="Screen Shot 2019-10-01 at 4 11 37 PM" src="https://user-images.githubusercontent.com/101482/66007167-32b48800-e466-11e9-94d2-66972d2fa5d5.png">

This does mean the size of the box will change from page to page, but that seems like an acceptable tradeoff to avoid seeing a lot of empty space in the box on many pages.

**Comment by ggeisler** [comment]
@jkeck asked about mobile behavior of the actions box, which I didn't specify in my original design. Below is the ideal behavior for the actions box on mobile, but note that from talking to @jkeck it sounds like it might be tricky to accomplish both the desired desktop behavior described in my previous comment (making the actions box width variable to accommodate just the content without the extra right-side empty space) and the mobile behavior below. The desktop behavior is the priority so if we can't get the mobile behavior below as well we can live with the current mobile behavior.

In general, on mobile I think we want the actions box to display at full-width up until the `medium` breakpoint, at which it will display side-by-side with the breadcrumbs. We are already doing this.

However, ideally we'd want the actions box contents to be more compact vertically on the smaller breakpoints, since the box has full-width there and we might be able to use the space better. Here are some examples at the smallest breakpoint:

### Actions box with all elements present
<img width="399" alt="Screen Shot 2019-10-01 at 2 09 28 PM" src="https://user-images.githubusercontent.com/101482/66001363-2de7d800-e456-11e9-9cf9-0343158cb630.png">

---

### Actions box without download links
<img width="399" alt="Screen Shot 2019-10-01 at 2 09 54 PM" src="https://user-images.githubusercontent.com/101482/66001404-43f59880-e456-11e9-8407-373072ac25b4.png">
 
---

### Actions box without download links or container info
<img width="399" alt="Screen Shot 2019-10-01 at 2 11 33 PM" src="https://user-images.githubusercontent.com/101482/66001436-553ea500-e456-11e9-901e-6277e2465272.png">

---

So the basic change would be to make the `.al-collection-id`, `.al-show-actions-box-request`, and `. al-show-actions-box-bookmarks` divs use `display: inline-block;` at the smaller breakpoints, so they all fit in the same row, along with some adjustments to horizontal spacing. 

One hitch is that sometimes the container info can be longer than my example, so the `inline-block` divs might still wrap to two rows in some cases.

**Comment by jkeck** [comment]
Okay, I think I'll have to cut bait on this as I'm a bit stumped at how to simultaneously accomplish title/breadcrumb content that flows around the actions box and keeping the actions box after the title/breadcrumb content.

I've taken a brief stab at a few improvements and pushed up a PR.  One thing that we could also do, if we decide to not go the float path is to put the upper metadata content into the same div as the title/breadcrumb so that it isn't pushed down passed the bottom of the actions box when it is taller than the title/breadcrumb.  This ends up changing how we generate configurations and allow downstream consumers to update the layout of the page.  We may want to have a larger discussion about what our goal is there as it will inform how much flexibility we have WRT having a lot of control to use flexbox vs. customization paths.

**Comment by jkeck** [comment]
Un-assigning myself incase anybody else wants to pick up the torch.

**Comment by ggeisler** [comment]
But note this is currently low-priority (and might not be very tractable) relative to other UX-related tickets that are open.

**Comment by seanaery** [comment]
Resolving this issue as part of a review of `arclight 1.0.x`. In the v1 layout, the component titles no longer collide with the actions box (which currently contains the bookmark checkbox).
