### ISSUE TITLE
Move "Navigation overview" into the Overview tab on Collection page

### ISSUE THREAD

**Issue by jvine** [projectblacklight/arclight#638]
Part C of #632.

The "Navigation overview" section of the sticky sidebar provides jump-to navigation to what can be extremely long content in the Overview tab. The sidebar is being removed; the tab section is being expanded from 9 to 12 columns; this navigation applies _only_ to the Overview tab. So the goal is to move it within the tab, while retaining its jump-to and sticky behaviour.

- [x] split the content of the Overview tab into 2 columns: content (9) and navigation (3).
  - On desktop, the content will be on the left; navigation on the right. 
  - On mobile, the content should wrap _below_ the navigation. 

- [x] move the navigation section into the new column, without its "card" container
  - On desktop, the list elements are stacked, right-aligned
  - On mobile, they are inline, left-aligned, and can wrap if necessary.

- [~] ~navigation section is sticky at the top of the page~ (splitting to another issue 🎟 - cv )

### Desktop
<img width="1154" alt="Nav on desktop" src="https://user-images.githubusercontent.com/6945691/63728979-79d1ac80-c81a-11e9-869b-21c973bd954f.png">

### Mobile
<img width="436" alt="Nav on mobile" src="https://user-images.githubusercontent.com/6945691/63728987-83f3ab00-c81a-11e9-86dd-460bd054b461.png">

### Behaviour

(Stickiness of app header and tabs will be addressed separately. This shows the behaviour & stickiness of the nav itself.)

![stickynav](https://user-images.githubusercontent.com/6945691/63728829-ebf5c180-c819-11e9-9ede-11e3191df2ca.gif)

**Comment by seanaery** [comment]
Hi @jvine - thanks for the thorough documentation on this ticket. Quick question: in mobile view should this nav be sticky too or is the stickiness only in desktop? I assume desktop only but thought I'd check :-)

**Comment by jvine** [comment]
Hi @seanaery - yes, it's meant to be sticky on mobile as well. It only takes a small amount of vertical space, and the amount of scrolling for a long intro is exponentially higher on  mobile, so it seems useful to have persistent anchors.

**Comment by seanaery** [comment]
@jvine Stickiness in the mobile view, where the overview nav turns horizontal is proving to be harder than I'd thought. I found a good [explanation of the issue here](https://medium.com/@elad/css-position-sticky-how-it-really-works-54cd01dc2d46#5abf). Just a heads-up that I'll need a bit more time to figure out a good way to do that. Suggestions welcome!

**Comment by jvine** [comment]
This is another thing you can split into a new issue if you want. I'm happy to take a look at it, but it will be easier when I can see it in action.
