### ISSUE TITLE
Add download links to component context/actions box when appropriate

### ISSUE THREAD

**Issue by ggeisler** [projectblacklight/arclight#640]
Part of #628.

When a collection's finding aid is available as a PDF and/or EAD xml file, we should display links in the component context/actions box at all component levels for that collection. The link(s) go at the bottom of the box, below the Request and Bookmark elements:

<img width="896" alt="Screen Shot 2019-08-26 at 4 18 21 PM" src="https://user-images.githubusercontent.com/101482/63729709-2b71dd00-c81d-11e9-9375-278c11b5c367.png">

The three examples above show how things look when there is A) only a PDF available, B) only an EAD file available, and C) when both files are available. 

When a collection doesn't have either a PDF and/or EAD xml file available to download, we omit those links entirely from the context/actions box.

## Previous related work

In the previous workcycle work was done that should make displaying the download links relatively easy(?) but as far as I know the requirements are not well documented and I'm not sure we actually have a working example of download links in our current demo instance. So here is some background in case it helps.

We added a feature that enables us to present links for downloading a collection PDF or EAD if one or both of those files have been named and stored appropriately. More specifically, based on comments by the developer who worked on ticket #371 I think the following rules apply:

- A finding aid PDF has to be named `unitid.pdf`, where `unitid` is the collection ID, I assume
- A finding aid EAD has to be named `unitid.xml`
- If either of those files exist and are intended for users to download, they need to be placed in the public/documents directory

Also, based on comments in PR #425, which closed #371, I think these other rules might apply:

- If either a PDF or EAD is intended to be downloadable, it needs to also be documented in a `/config/downloads.yml` file like this:

```
sample_unitid:
  pdf:
    href: 'http://example.com/sample.pdf'
    size: '1.23MB'
  ead:
    href: 'http://example.com/sample.xml'
    size: 123456
```
- Because we have changed the way we want the download links to be available in the UI, we'll have to also update the locale strings in `config/locales/arclight.en.yml` to reflect the new strings used in the mockups above:

```
        download:
          default: 'Download'
          pdf: 'Collection PDF (%{size})'
          ead: 'Collection EAD (%{size})'
```

Note that I'm not sure we ever created real examples in the demo instance of ArcLight to see how this all works in practice.

### Icons

Icon | Source | SVG code
------------ | ----------| -------------
pdf | Font Awesome [[file-pdf](https://fontawesome.com/icons/file-pdf?style=regular)] | `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 384 512"><path d="M369.9 97.9L286 14C277 5 264.8-.1 252.1-.1H48C21.5 0 0 21.5 0 48v416c0 26.5 21.5 48 48 48h288c26.5 0 48-21.5 48-48V131.9c0-12.7-5.1-25-14.1-34zM332.1 128H256V51.9l76.1 76.1zM48 464V48h160v104c0 13.3 10.7 24 24 24h104v288H48zm250.2-143.7c-12.2-12-47-8.7-64.4-6.5-17.2-10.5-28.7-25-36.8-46.3 3.9-16.1 10.1-40.6 5.4-56-4.2-26.2-37.8-23.6-42.6-5.9-4.4 16.1-.4 38.5 7 67.1-10 23.9-24.9 56-35.4 74.4-20 10.3-47 26.2-51 46.2-3.3 15.8 26 55.2 76.1-31.2 22.4-7.4 46.8-16.5 68.4-20.1 18.9 10.2 41 17 55.8 17 25.5 0 28-28.2 17.5-38.7zm-198.1 77.8c5.1-13.7 24.5-29.5 30.4-35-19 30.3-30.4 35.7-30.4 35zm81.6-190.6c7.4 0 6.7 32.1 1.8 40.8-4.4-13.9-4.3-40.8-1.8-40.8zm-24.4 136.6c9.7-16.9 18-37 24.7-54.7 8.3 15.1 18.9 27.2 30.1 35.5-20.8 4.3-38.9 13.1-54.8 19.2zm131.6-5s-5 6-37.3-7.8c35.1-2.6 40.9 5.4 37.3 7.8z"/></svg>`
ead | Font Awesome [[file-code](https://fontawesome.com/icons/file-code?style=regular)] | `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 384 512"><path d="M149.9 349.1l-.2-.2-32.8-28.9 32.8-28.9c3.6-3.2 4-8.8.8-12.4l-.2-.2-17.4-18.6c-3.4-3.6-9-3.7-12.4-.4l-57.7 54.1c-3.7 3.5-3.7 9.4 0 12.8l57.7 54.1c1.6 1.5 3.8 2.4 6 2.4 2.4 0 4.8-1 6.4-2.8l17.4-18.6c3.3-3.5 3.1-9.1-.4-12.4zm220-251.2L286 14C277 5 264.8-.1 252.1-.1H48C21.5 0 0 21.5 0 48v416c0 26.5 21.5 48 48 48h288c26.5 0 48-21.5 48-48V131.9c0-12.7-5.1-25-14.1-34zM256 51.9l76.1 76.1H256zM336 464H48V48h160v104c0 13.3 10.7 24 24 24h104zM209.6 214c-4.7-1.4-9.5 1.3-10.9 6L144 408.1c-1.4 4.7 1.3 9.6 6 10.9l24.4 7.1c4.7 1.4 9.6-1.4 10.9-6L240 231.9c1.4-4.7-1.3-9.6-6-10.9zm24.5 76.9l.2.2 32.8 28.9-32.8 28.9c-3.6 3.2-4 8.8-.8 12.4l.2.2 17.4 18.6c3.3 3.5 8.9 3.7 12.4.4l57.7-54.1c3.7-3.5 3.7-9.4 0-12.8l-57.7-54.1c-3.5-3.3-9.1-3.2-12.4.4l-17.4 18.6c-3.3 3.5-3.1 9.1.4 12.4z"/></svg>`

#### Color
`#6C757D` - You should be be able to use the `$secondary` variable in .scss files.

#### Size and positioning
I'm guessing that making the icon height and width `1rem` might work. Elsewhere we use the SCSS below to style icons so the other attributes might be useful but also might not be necessary. Just FYI. I can also fine-tune things later.

```
.blacklight-icons svg {
  height: 1rem;
  width: 1rem;
  top: .125rem;
  position: relative;
}
```

**Comment by anarchivist** [comment]
See #683 for the actionable work on constructing links to EAD files - we can probably take a similar approach for PDFs.

**Comment by jkeck** [comment]
See #777 for more details about how to implement the links if/once that is merged.

**Comment by jkeck** [comment]
Currently we only show an "actions box" for components.  Should we be rendering links to download the entire collection both at the component and collection levels?

**Comment by jrgriffiniii** [comment]
http://www.loc.gov/ead/tglib/elements/unitid.html features an example in which these IDs reference an entire collection.

**Comment by jrgriffiniii** [comment]
https://github.com/projectblacklight/arclight/blob/master/app/assets/javascripts/arclight/collection_navigation.js#L20 has been stripping `<a>` elements from the AJAX-requested content, this needs to be avoided in order to properly preserve the HTML in the Collection Context.

**Comment by seanaery** [comment]
@jrgriffiniii That line only removes the link to the currently-viewed item ( per #515 ). Any components that aren't the currently-viewed one still have their links. Though the current display is confusing -- the linked part of the line (the title) is not styled to be distinguishable from the non-linked text (the extent in the beginning of the line).

**Comment by ggeisler** [comment]
@jkeck:
> Currently we only show an "actions box" for components. Should we be rendering links to download the entire collection both at the component and collection levels?

Yes, definitely. Sorry that wasn't clear, but by "we should display links in the component context/actions box at all component levels for that collection" I was considering the collection itself to be one of the component levels (the top level).

**Comment by ggeisler** [comment]
@jrgriffiniii @seanaery I'm not sure this is relevant to your discussion above that references #515, but note that that ticket was written before we revised the way we intend to display the collection contents/context, so that confusing display will go away after #673 is done.

**Comment by jrgriffiniii** [comment]
Closed by https://github.com/projectblacklight/arclight/pull/808, but please freely reopen this if there are design improvements which should be introduced for these interface components.
