### ISSUE TITLE
Tabs and tab contents use 12 columns

### ISSUE THREAD

**Issue by jvine** [projectblacklight/arclight#645]
Once the sidebar is removed, the full width of the show page is available.

- [ ] tabs and `tab-content` should use 12 columns on all devices
- [ ] tabs should use `nav-fill` to fill the width of the page. 2-word labels may wrap within a tab.

Note that component pages will no longer have an Overview tab (#630), and File-level pages will no longer have an Online content tab, so the number of tabs will vary by the current level in the hierarchy.

**Collection desktop**
<img width="971" alt="desktop 4" src="https://user-images.githubusercontent.com/6945691/63732053-231e9f80-c827-11e9-82ca-2c2bd0b6a5cf.png">
**Collection mobile**
<img width="300" alt="mobile 4" src="https://user-images.githubusercontent.com/6945691/63732051-231e9f80-c827-11e9-8de9-f2dc2e2008e5.png">

**Component desktop**
<img width="960" alt="desktop 3" src="https://user-images.githubusercontent.com/6945691/63732094-58c38880-c827-11e9-8959-e08ccdc0db5a.png">
**Component desktop - no online content**
<img width="946" alt="desktop 3 disabled" src="https://user-images.githubusercontent.com/6945691/63732177-c2dc2d80-c827-11e9-9a9c-b1dc4e859335.png">
**Component mobile**
<img width="300" alt="mobile 3" src="https://user-images.githubusercontent.com/6945691/63732093-58c38880-c827-11e9-944e-eac879d4a1e7.png">

**File desktop**
<img width="961" alt="desktop 2" src="https://user-images.githubusercontent.com/6945691/63732109-6da01c00-c827-11e9-9738-b3a2d903f274.png">
**File mobile**
<img width="300" alt="mobile 2" src="https://user-images.githubusercontent.com/6945691/63732110-6da01c00-c827-11e9-8b84-50939ebf11d6.png">

**Comment by seanaery** [comment]
@jvine - The images in this ticket suggest keeping these nav elements as `nav-pills` though most of the related tickets under #632 imply `nav-tabs`. I think these do look better as tabs--just looking to confirm that's the plan. Also, the changes in #638 do create horizontal pills in the Overview tab in mobile view just below these main tabs, which would probably be confusing if it was just two rows of horizontal pills stacked...

**Comment by jvine** [comment]
Ah sorry, the difference in the mockups is not really meaningful, just an artifact of drawing from scratch in XD vs in-browser mockups. I think we would prefer the `nav-tabs` style, but I ran into an issue when I was experimenting with them. Tab labels will wrap in some contexts, and the `nav-tabs` style doesn't seem to handle a mix of 2-line and 1-line labels. This looks less broken in the `nav-pills` style. 

<img width="357" alt="Screen Shot 2019-09-03 at 9 36 40 AM" src="https://user-images.githubusercontent.com/6945691/64191899-62a04980-ce2e-11e9-83ff-902ed9aced94.png">

**Comment by seanaery** [comment]
@jvine Aha, I see what you mean about the tabs. At super-narrow viewport widths, it'll get tricky to get nice tabs just using out-of-the-box Bootstrap. Even with flexbox and a `nav-fill` class, we'll get this kind of wrapping:

![Screen Shot 2019-09-04 at 12 03 58 PM](https://user-images.githubusercontent.com/3933756/64273381-2c86c680-cf0f-11e9-80e0-cc086081d5f4.png)

![Screen Shot 2019-09-04 at 10 45 01 AM](https://user-images.githubusercontent.com/3933756/64273394-31e41100-cf0f-11e9-88a4-077fd19a478a.png)

...which is functional but less-than-ideal. What I'm hoping to avoid though is this (pills used for both the main nav and for the overview nav):
Screen Shot 2019-09-04 at 10.44.29 AM

I'm wondering if we might be able to split out the mobile tab conundrum as its own issue so it doesn't prevent the primary tab layout revision from moving forward. There are some possible approaches like this one ( https://www.codeply.com/go/Loo3CqsA7T ) that might fit the bill but they'd take a bit more investigation (and introduce a considerable amount of new JS to the app).

**Comment by jvine** [comment]
Yes, it's fine to split the issue out. Agree that we don't want pills on top of pills. Our goal is to find a way to keep the tabs on one row on mobile, even if the words have to wrap. Will add more in the new ticket.

**Comment by camillevilla** [comment]
Most of this issue was addressed by #690. Further work on wrapping tabs has been split out to #717
