### ISSUE TITLE
Is there a better way to access parent components for a given element in our traject config?

### ISSUE THREAD

**Issue by mejackreed** [projectblacklight/arclight#653]
@estelendur brought this up in https://github.com/projectblacklight/arclight/pull/610/files#r317277920

We should do some analysis and determine if there is a better pattern for this than dropping into the parent document.

**Comment by seanaery** [comment]
I completed some analysis on alternative ways to get at parent (and other ancestor) components. I recommend using xpath to traverse the tree wherever possible, including cases like this where we're in a component context and need to access the parent node and its other descendants. 

Some notes:
- Less code required
- Seems easier to read/understand
- When in the context of a component node, you can use [xpath axes](https://www.w3schools.com/xml/xpath_axes.asp) to get to nodes relative to the current component (ancestors, etc.).

For instance:
```ruby
# Get the <accessrestrict> from the closest ancestor that has one (includes top-level)
to_field 'parent_access_restrict_ssm' do |record, accumulator|
  accumulator.concat Array
    .wrap(record.xpath('(./ancestor::*/xmlns:accessrestrict)[last()]/*[local-name()!="head"]')
    .map(&:text))
end
```

Another example:
```ruby
# Get the <userestrict> from self OR the closest ancestor that has one (includes top-level)
to_field 'parent_access_terms_ssm' do |record, accumulator|
  accumulator.concat Array
    .wrap(record.xpath('(./ancestor-or-self::*/xmlns:userestrict)[last()]/*[local-name()!="head"]')
    .map(&:text))
end
```
These rewritten indexing rules can be seen in PR #753 for comparison with rules that lean more on ruby for finding ancestor nodes.

I'm unsure about any performance implications going this route and am certainly open to other alternatives :-)
