### ISSUE TITLE
Index EAD web url

### ISSUE THREAD

**Issue by estelendur** [projectblacklight/arclight#663]
If an EAD provides an indexable URL for itself, use that for downloads in addition to the `downloads.yml` file. There may be a `URL` attribute inside `<eadid>`.

Extends the work done for #640. The same URL can be used for populating an Aeon web url request as in #643.

**Comment by anarchivist** [comment]
I think this can be closed ...

**Comment by archivalGrysbok** [comment]
Was this accomplished under a different issue? I'm trying to figure out how to use the url in the eadid to populate the downloads box. Thank you :)
