### ISSUE TITLE
Add sort option to group search results by collection

### ISSUE THREAD

**Issue by ggeisler** [projectblacklight/arclight#676]
Part of #667.

To enable the user to switch to a view of search results where the results are grouped by collection, we need to add an option to the current sort menu:

<img width="660" alt="Screen Shot 2019-08-29 at 3 15 26 PM" src="https://user-images.githubusercontent.com/101482/63980262-e72a4b00-ca6f-11e9-8f50-ecf261ed0a60.png">

- [ ] Add a divider after the last item in the current dropdown menu: `<div class="dropdown-divider"></div>`

- [ ] Add a new option with the label: `Group by collection`. When selected, this option should take the user to the grouped view of search results, which will be described in forthcoming tickets.

**Comment by jvine** [comment]
Deprecate in favour of #706 so we can assess the sort behaviour; may return to this depending on outcome.

**Comment by mejackreed** [comment]
Deprecated in favor of #706
