### ISSUE TITLE
Show "Online content" tab as a search result with pagination

### ISSUE THREAD

**Issue by jvine** [projectblacklight/arclight#679]
Part of #678 

The "Online content" tab displays a search result of the items in the collection (or component). Currently it displays 10 items with no pagination.

To whomever picks this up:
 - You have the ability to spin out pieces of this based off performance implications or complexity (pagination, suggesting alternate patterns).

- [x] Format the results as in the **list view** of search results #669 with these changes:
   - [x] Suppress box/folder container info
   - [x] Add a count of the number of `<dao>` links in the component (3)
- [x] Add the `page-links` section at the top (1)
- [ ] Add the 'per-page' control to allow the user to see more than 10 results at a time (2)
- [x] Sort the results in collection order (so they occur in the same order they would appear in the collection tree)
- [ ] Add the full pagination `nav` at the bottom. (4)
- [x] Add the total count of items as a badge to the tab label. (5)

<img width="998" alt="online content search result" src="https://user-images.githubusercontent.com/6945691/63986696-ef8f7f80-ca89-11e9-8715-8127cca853b0.png">

**Comment by labradford** [comment]
Putting this back on ready in case someone else wants to pick this up. Some of this work might rely on completing #680 (online content tab showing search results)

**Comment by gordonleacock** [comment]
Hmmm, I may have created an overlapping issue: Show online content for level’s children in a search view in “Online content” tab #927.

**Comment by seanaery** [comment]
Resolving this issue as part of a review of `arclight 1.0.x`. Online content is now displayed as an index view with facets and pagination/sort widgets.
