### ISSUE TITLE
Define a programmatic approach to constructing download links

### ISSUE THREAD

**Issue by mejackreed** [projectblacklight/arclight#683]
`downloads.yml` already provides a useful mechanism for a repository to define individual downloads for a given collection-level description. Extend this to enable the following:

 - [x] a programmatic construction of a url 

The intent is to allow ArcLight implementers to customize this locally, add custom logic, call an external API, etc., as they need to.

**Comment by anarchivist** [comment]
Example:

* Given a collection-level description:
  * has an eadid of InU-Li-VAA9510
  * associated with an ArcLight repository code of `lilly`
  * and there's a configured method to use URL template like `http://purl.dlib.indiana.edu/iudl/findingaids/$repository/encodedtext/$eadid`

then generate the link to the EAD like `http://purl.dlib.indiana.edu/iudl/findingaids/lilly/encodedtext/InU-Li-VAA9510`

**Comment by camillevilla** [comment]
Further discussion in planning 9/11: 
- minimal "out of the box" case ignores downloads
- stub some kind of method that returns a URL, implementer must add logic

Questions: 
- how did we set up our applicaioin helpers? Are they easily overridable?
