### ISSUE TITLE
Pagination nav not wrapping on mobile

### ISSUE THREAD

**Issue by jvine** [projectblacklight/arclight#687]
The pagination nav at the bottom of the search results seems to need an explicit `flex-wrap: wrap;`. On mobile, the `<li>` elements don't wrap, and it means you have to scroll the page left to see the full nav.

<img width="289" alt="nav 1" src="https://user-images.githubusercontent.com/6945691/64053997-da722980-cb39-11e9-87ef-6a45ecb757a7.png"> <img width="293" alt="nav 2" src="https://user-images.githubusercontent.com/6945691/64054002-e362fb00-cb39-11e9-9aee-a624517ee3b3.png">

**Comment by labradford** [comment]
This is fixed upstream in Blacklight. We will get the fix in the next release
