### ISSUE TITLE
List view for grouped search results - F - Collection result message

### ISSUE THREAD

**Issue by mejackreed** [projectblacklight/arclight#704]
Split out of #681 

<img width="635" alt="Screen Shot 2019-08-29 at 4 20 50 PM" src="https://user-images.githubusercontent.com/101482/64035840-9b76b080-cb06-11e9-8ef7-bab5fa7ae551.png">

**F: Collection result message** - There are two parts to this, unless the collection group has 3 or fewer document matches, in which case only the first part is needed.

- [x] Show the result message for the collection below the collection box. Indent by ~15px
- [x] The first part of the message is a static string that says `Top 3 results`
- [x] The second part of the message is a link in the form of "view all x" where x is the number of documents matched in that collection (I think this is the `numFound` value in the Solr grouped response, but don't trust me). Selecting the link should take the user to the normal, ungrouped results for the current query, **with that collection added as a constraint**.
- [x] If a collection returns 3 or fewer documents, change the first, static string to `x results` (where x is the count for the collection) and omit the second, linked part.

**Comment by camillevilla** [comment]
See TODO added in #718
