### ISSUE TITLE
Update list view of search results - C - Online content label

### ISSUE THREAD

**Issue by mejackreed** [projectblacklight/arclight#709]
Split out of #669 

<img width="877" alt="Screen Shot 2019-08-28 at 4 36 48 PM" src="https://user-images.githubusercontent.com/101482/63900031-11b6ce00-c9b4-11e9-8809-6c47cee4f009.png">

**C: Online content label** - This is new and should match what we do in the collection contents and online contents tabs. Not all items will have this label.

- [x] If the result item has digital content and the item is a file, show a green image icon.
- [x] If the result item is a parent container that either has digital content or contains at least one child with digital content, show the text "Online content" in green (#28A745).

**Comment by labradford** [comment]
@ggeisler  I wanted to get clarification on the requirements for this ticket. When displaying the "online content" label, are we using the same logic as before with the exception of showing an icon when the item is of the type file? The current logic for displaying the online content label stays the same? (like for collections or parent containers). Or is there a change to the existing way the label is shown?

**Comment by ggeisler** [comment]
@labradford Yep, logic is unchanged, just replacing the "online content" label with the icon.

**Comment by labradford** [comment]
Closing this ticket as it is being replaced by #794
