### ISSUE TITLE
Force all 4 tabs inline for mobile widths

### ISSUE THREAD

**Issue by camillevilla** [projectblacklight/arclight#717]
Split out from #645 / see discussion there

![Screen Shot 2019-09-04 at 12 03 58 PM](https://user-images.githubusercontent.com/3933756/64273381-2c86c680-cf0f-11e9-80e0-cc086081d5f4.png)

![Screen Shot 2019-09-04 at 10 45 01 AM](https://user-images.githubusercontent.com/3933756/64273394-31e41100-cf0f-11e9-88a4-077fd19a478a.png)

**Comment by estelendur** [comment]
![image](https://user-images.githubusercontent.com/10409866/64441597-30941f00-d09c-11e9-8248-303be91387af.png)
^ In this situation, do we require the user to scroll sideways?
