### ISSUE TITLE
Add a "scope" dropdown to the search bar

### ISSUE THREAD

**Issue by jvine** [projectblacklight/arclight#719]
Part of #716 

- [x] **Add a dropdown to the search bar, in front of the form.**
   - dropdown uses the same button+menu structure as the "Sort" dropdown
   - add `btn-lg` class
   - button text is "Search" + user's / default selection
   - selections are:
      - all collections
      - this collection

<img width="506" alt="Screen Shot 2019-09-04 at 2 34 44 PM" src="https://user-images.githubusercontent.com/6945691/64293366-48936380-cf21-11e9-87cd-1e2b7ef4cf56.png">

- [x] **If there is no current collection selected (*), disable "this collection"**
<img width="251" alt="Screen Shot 2019-09-04 at 2 43 24 PM" src="https://user-images.githubusercontent.com/6945691/64293902-72995580-cf22-11e9-8d09-50b698c52ca8.png">

- [x] **If there is a current collection selected (*) make "this collection" the default**
<img width="254" alt="Screen Shot 2019-09-04 at 2 43 56 PM" src="https://user-images.githubusercontent.com/6945691/64293912-7927cd00-cf22-11e9-9504-259d24c3c3fe.png">

### * "Current collection selected"

If the user is **on any component page**, searching within the collection that component belongs to should be the default behaviour. 

If the user is **in a search result with a collection limit applied**, they are de facto searching within "this collection" until the collection limit is removed. I think the search box should reflect that: so the default would be "this collection".

**That implies that selecting "all collections" in the dropdown _would also_ remove the collection limit.**

**Comment by jkeck** [comment]
Two quick questions:

1. Should the drop down behave like sort and per-page (e.g. should clicking on an option in the drop down change the search context)?
1. Should the `this collection` option be enabled/default on any search result w/ a collection facet selected as well as any show page?
    * This is based on the assumption that any show page is either showing a collection or a component w/i the collection and a search initiated there by default should be w/i that collection context.

**Comment by jvine** [comment]
1. Not sure if I'm understanding the question correctly, but selecting an option in the dropdown does not change any anything about the current search results. It only sets the target for the next search submitted by the user. 

2. I think `this collection` should be default if there is a collection facet selected, because it is, in fact, what is happening when the user submits the next search. The question is, would selecting `all collections` at that point remove the current facet when the search is submitted? It seems logical to me but I don't know how it plays with standard Blacklight behaviour.
