### ISSUE TITLE
Relevance: provide documentation on Solr configuration (especially boost/query analysis)

### ISSUE THREAD

**Issue by anarchivist** [projectblacklight/arclight#724]
Per product owner feedback, we should provide some degree documentation on how Solr can be configured for ArcLight. This specifically has come up in the context of explaining how things like boost and query analysis (e.g. stemming) can be configurable. The assumption here is that we can't provide something exhaustive, and that some implementers (e.g. archivists/product owners) may be new to Solr. We thus need to provide some pointers in terms what could be tweaked, and potential references to things to try, other resources, etc.

Refs #532, #597.

**Comment by christinach** [comment]
Started a google doc https://docs.google.com/document/d/1vwji-y7VLMaemLUTN0zdQ3iYdL9EJlZrLfx_HhIs8vs/edit.

**Comment by christinach** [comment]
https://docs.google.com/document/d/1vwji-y7VLMaemLUTN0zdQ3iYdL9EJlZrLfx_HhIs8vs/edit?usp=sharing

**Comment by christinach** [comment]
Added a new wiki page https://github.com/projectblacklight/arclight/wiki/Configuring-Solr-and-Search-Relevancy

**Comment by seanaery** [comment]
I have created new documentation for this, especially reflecting the current state of 1.x, at the existing wiki page: https://github.com/projectblacklight/arclight/wiki/Configuring-Solr-and-Search-Relevancy

@christinach Thanks for your work on this back in 2019! While I added new info to the doc, I retained the info you provided then, as it all looks to be still useful.
