### ISSUE TITLE
Relevance: analyze stemming behavior

### ISSUE THREAD

**Issue by anarchivist** [projectblacklight/arclight#725]
On the 2019-09-04 PO call, we talked about matches (involving names) where names that appeared in e.g. a title were ranked lower than than those containing a stemmed form of the query. For example, the name `Eugene` is presumably getting stemmed to `eugen`, which also matches `eugenics`. 

* What are our options for adjusting this?
* Are there specific fields that do not benefit from stemming?

**Comment by cbeer** [comment]
[`KeywordRepeatFilterFactory`](https://lucene.apache.org/solr/guide/6_6/language-analysis.html#LanguageAnalysis-KeywordRepeatFilterFactory) may be sufficient in many cases to address stemmed vs unstemmed relevancy.
