### ISSUE TITLE
Better support known-item searching for collections

### ISSUE THREAD

**Issue by anarchivist** [projectblacklight/arclight#726]
Users will often want to search for collections by title or collection/call number (i.e. `unitid`). Query terms that match in either of these fields should be ranked highly, above any component or collection-level matches that don't match on thse.

Examples:

* A query for a collection with call number "MS 1934" should match if someone searches for "MS1934"
* See also #257 

Refs #532 and #597.

**Comment by billdueber** [comment]
We could split the suggest handlers up by type, so 99% of the time folks could get autocomplete for a known collection name.
