### ISSUE TITLE
Pretty print EAD fixtures

### ISSUE THREAD

**Issue by camillevilla** [projectblacklight/arclight#739]
Kudos to @seanaery for bringing this up at community sprint standup today. The request here is to pretty print our fixtures for easier debugging. Bonus: add some auto-linting tool for new fixtures.

**Comment by seanaery** [comment]
Hi @billdueber --

My primary interest in making this change is just for XML tag indentation on our (currently limited set of) fixtures. Most of them are already pretty consistently indented (which really helps for understanding nesting, collapsing/expanding, troubleshooting, etc.). But this one isn't:
https://github.com/projectblacklight/arclight/blob/master/spec/fixtures/ead/nlm/ncaids544-id-test.xml

I'm not too worried about other kinds of cleanup (e.g., whitespace stripping).

I'm also less concerned about the [EADs in the demo app](https://github.com/sul-dlss/arclight-demo/tree/master/data/ead). Most of those look well-indented (except for Michigan's `<dsc>` sections).
