### ISSUE TITLE
Multiple notes of the same type on collection and component show pages should be separated by paragraphs

### ISSUE THREAD

**Issue by anarchivist** [projectblacklight/arclight#742]
Multiple notes of the same type should be separated by paragraphs on collection and component show pages. These should include the following; this will likely mean both a change to the generator for the catalog controller, and the demo app's catalog controller. 

* Access restrictions
* Use restrictions (a.k.a. terms of access)
* Parent access restrictions (on components only)
* Abstract
* Acquisition information
* Appraisal
* Custodial history
* Processing information
* Arrangement (not displayed in demo app?)
* Accruals (not displayed in demo app?) 
* Physical/technical requirements (not displayed in demo app?)
* Physical location (not displayed in demo app?)
* Rules or conventions (not indexed?)

## Examples

<details><summary>Collection view</summary>

**Before**

![Screen Shot 2019-09-09 at 9 49 22 AM](https://user-images.githubusercontent.com/73732/64550282-6aa53100-d2e7-11e9-9955-37f2a10d7be4.png)

**After**

![Screen Shot 2019-09-09 at 9 50 16 AM](https://user-images.githubusercontent.com/73732/64550298-72fd6c00-d2e7-11e9-9f83-1d1601a0e660.png)
</details>

<details><summary>Component view</summary>

**Before**

![Screen Shot 2019-09-09 at 9 21 15 AM](https://user-images.githubusercontent.com/73732/64550076-f10d4300-d2e6-11e9-8e9d-d9e8af8f6688.png)

**After**

![Screen Shot 2019-09-09 at 9 22 34 AM](https://user-images.githubusercontent.com/73732/64550089-f66a8d80-d2e6-11e9-8a18-c893642aa06e.png)
</details>

**Comment by seanaery** [comment]
Hi @anarchivist --

These look to me like the EAD elements corresponding to your list--can you confirm? Also, what field or fields hold "rules or conventions"?

|Item|Element|
|---|---|
|Access restrictions|`<accessrestrict>`|
|Use restrictions (a.k.a. terms of access)|`<userestrict>`|
|Parent access restrictions (on components only)|ancestor `<accessrestrict>`|
|Abstract|`<abstract>`|
|Acquisition information|`<acqinfo>`|
|Appraisal|`<appraisal>`|
|Custodial history|`<custodhist>`|
|Processing information|`<processinfo>`|
|Arrangement (not displayed in demo app?)|`<arrangement>`|
|Accruals (not displayed in demo app?)|`<accruals>`|
|Physical/technical requirements (not displayed in demo app?)|`<phystech>`|
|Physical location (not displayed in demo app?)|`<physloc>`|
|Rules or conventions (not indexed?)|`???`|

Thanks!

**Comment by anarchivist** [comment]
Rules or conventions are `<descrules/>` in EAD2002, and `<conventiondeclaration/>` and `<localtypedeclaration/>` in EAD3. In both cases, these are only top-level elements.
