### ISSUE TITLE
Format @render attributes for display (bold, italic, etc.)

### ISSUE THREAD

**Issue by noahgh221** [projectblacklight/arclight#761]
As of 9/11, the demo app is not applying any formatting based on values of the `@render`, which may appear as an attribute of the `<title>`, `<emph>` or `<titleproper>` elements.

From the EAD2002 Tag Library, here are possible values of the render attribute:

RENDER -- The formatting of the content of an element is controlled for display and print purposes. Available in <emph>, <title>, and <titleproper>. See also ALTRENDER. Values are:

altrender
bold
doublequote
bolddoublequote
bolditalic
boldsinglequote
boldsmcaps
boldunderline
italic
nonproport
singlequote
smcaps
sub
super
underline

Here is an example fixture that contains `<title @render="italic">Daily and Weekly Sun</title>`: https://arclight-demo.projectblacklight.org/catalog/ahstephens#background

Current display in demo app:
![image](https://user-images.githubusercontent.com/7328518/64720734-26599280-d499-11e9-9e28-9b2f060c38c0.png)

**Comment by seanaery** [comment]
Looks like we'll probably need to build the equivalent of this (from SolrEAD) using Traject:
https://github.com/awead/solr_ead/blob/master/lib/solr_ead/formatting.rb

**Comment by jlhardes** [comment]
I know this is closed now but this change might be what has created the problem reported in #990  - Title element not showing unless render attribute included
