### ISSUE TITLE
Add consistent "Online content" for compact view

### ISSUE THREAD

**Issue by mejackreed** [projectblacklight/arclight#766]
Prereqs: #765 and #709 

![](https://user-images.githubusercontent.com/101482/63957757-e37dd080-ca3d-11e9-993d-6c1e89420ec7.png)

See #671 for more details

**Comment by gordonleacock** [comment]
Hi Jack, was this resolved by the PR https://github.com/projectblacklight/arclight/pull/797?

If not, can you clarify the issue a bit?

**Comment by mejackreed** [comment]
@gordonleacock Using the implementation in #797, I'm not seeing that icon while in "compact" view.

URL to check:
http://127.0.0.1:3000/?q=&search_field=all_fields&utf8=%E2%9C%93&view=compact

![Screen Shot 2019-09-17 at 3 52 36 PM](https://user-images.githubusercontent.com/1656824/65082436-34a92200-d963-11e9-9e26-04fad38e61b6.png)
