### ISSUE TITLE
Bug - bookmark toggle throws js error

### ISSUE THREAD

**Issue by labradford** [projectblacklight/arclight#769]
On the bookmark toggle checkbox, you are able to check/uncheck each bookmark box once. When you click a second time, a JS alert appears with an error. Reloading the page allows you to check/uncheck again, but only once for each checkbox.

**Comment by christinach** [comment]
I can't seem to reproduce this error.

**Comment by jkeck** [comment]
I think this may be a turbolinks issue.  If you go from the home page, click on collections, and try to bookmark, then unbookmark a record, you get an error.  If you refresh that same page and bookmark/unbookmark the error does not occur.

**Comment by christinach** [comment]
thanks @jkeck  I'll check again

**Comment by christinach** [comment]
now I see it thanks @jkeck !

**Comment by christinach** [comment]
A first approach was to remove `turbolinks` when generating the engine: https://github.com/projectblacklight/arclight/tree/remove-turbolinks. I tested it locally with a local copy of Blacklight and the bookmark check/uncheck was setting the attribute successfully. When I tested a collection item I could still trigger the same error `[HTTP/1.1 422 Unprocessable Entity ]`. 
second approach: I put back the turbolinks and added the `refreshCSRFTokens` function to refresh the tokens when loading turbolinks https://github.com/projectblacklight/arclight/tree/769-refresh-csrftokens. This was successful for the collection level but still wouldn't work for the form in a collection level item.

**Comment by seanaery** [comment]
Looks like this issue is specific to Rails 5.2 and was reported here as a Blacklight issue:
https://github.com/projectblacklight/blacklight/issues/2002

More info here on Penn State's Blacklight code repo:
https://github.com/psu-libraries/psulib_blacklight/issues/71

**Comment by estelendur** [comment]
So... we can disable forgery protection on the bookmark checkboxes, or we can figure out a fix to the *problem*, which is probably that the csrf token on the bookmark form is not updated when we submit the form and get a response from the server. Either way the core issue is with code that is present in Blacklight.

**Comment by jcoyne** [comment]
I'm not able to duplicate this.  Am I doing it right?


![arclight](https://user-images.githubusercontent.com/92044/66143083-3104d480-e5cc-11e9-8a7d-b2e758366c93.gif)

**Comment by mejackreed** [comment]
Try it on the Bookmarks page. I'm seeing it happen there. We are seeing these things intermittent in odd places.

**Comment by jcoyne** [comment]
Okay, I see it on the Arclight bookmarks page, but curiously I can't see it on the http://demo.projectblacklight.org/.   Where is the source for the arclight-demo?

**Comment by mejackreed** [comment]
Arclight-Demo here: https://github.com/sul-dlss/arclight-demo

Arclight codebase: https://github.com/projectblacklight/arclight

**Comment by jcoyne** [comment]
One difference I notice between the arclight and the blacklight demo site is that the latter is always submitting the request with an X-CSRF-Token header that matches the meta tag.

**Comment by seanaery** [comment]
Resolving this issue as part of a review of `arclight 1.0.x`. This no longer happens with a new vanilla app generated in v1.
