### ISSUE TITLE
Update icon used for online content

### ISSUE THREAD

**Issue by ggeisler** [projectblacklight/arclight#782]
Related to #779.

We currently use a Bootstrap badge with the `badge-success` class to indicate an item has online content. We want to replace that with an icon. So it would look more like:

<img width="868" alt="Screen Shot 2019-09-13 at 4 02 28 PM" src="https://user-images.githubusercontent.com/101482/64899500-850d4080-d640-11e9-9970-b1ab75e13340.png">

The same icon should replace the badge in all contexts it is used:

- Search result items
- Collection contents/context tab
- Online content tab

I think the same size and color will work for all contexts.

### Color
`#28a745` or `$green` Bootstrap color variable 

### Size
```
  height: 24px;
  width: 24px;
```

Icon | Source | SVG code
------------ | ----------| -------------
online_content | Font Awesome [[photo-video](https://fontawesome.com/icons/photo-video?style=solid)] | `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 640 512"><path d="M608 0H160a32 32 0 0 0-32 32v96h160V64h192v320h128a32 32 0 0 0 32-32V32a32 32 0 0 0-32-32zM232 103a9 9 0 0 1-9 9h-30a9 9 0 0 1-9-9V73a9 9 0 0 1 9-9h30a9 9 0 0 1 9 9zm352 208a9 9 0 0 1-9 9h-30a9 9 0 0 1-9-9v-30a9 9 0 0 1 9-9h30a9 9 0 0 1 9 9zm0-104a9 9 0 0 1-9 9h-30a9 9 0 0 1-9-9v-30a9 9 0 0 1 9-9h30a9 9 0 0 1 9 9zm0-104a9 9 0 0 1-9 9h-30a9 9 0 0 1-9-9V73a9 9 0 0 1 9-9h30a9 9 0 0 1 9 9zm-168 57H32a32 32 0 0 0-32 32v288a32 32 0 0 0 32 32h384a32 32 0 0 0 32-32V192a32 32 0 0 0-32-32zM96 224a32 32 0 1 1-32 32 32 32 0 0 1 32-32zm288 224H64v-32l64-64 32 32 128-128 96 96z"/></svg>`

**Comment by christinach** [comment]
Is this resolved by https://github.com/projectblacklight/arclight/pull/794 ?
