### ISSUE TITLE
Link to collection from collection title in grouped search results

### ISSUE THREAD

**Issue by noahgh221** [projectblacklight/arclight#787]
Issue https://github.com/projectblacklight/arclight/issues/702 seems to indicate there was a decision NOT to provide a link to the collection from the collection title in grouped search results?

I'd recommend providing a link here (from "Frank Clyde Brown Papers" title in the screenshot below)

![image](https://user-images.githubusercontent.com/7328518/64974397-bc673180-d87a-11e9-929b-3925af1a449d.png)

**Comment by anarchivist** [comment]
Tagging @ggeisler and @jvine, since there's design feedback here.

**Comment by ggeisler** [comment]
Yep, we should link the collection title here.

We'll explore later whether we can and should style the link in a way other than the default styling, but for now we should do this first step of adding the link.
