### ISSUE TITLE
Some Creators don't get indexed or displayed

### ISSUE THREAD

**Issue by seanaery** [projectblacklight/arclight#788]
On the top-level and component levels, the Creator is determined by an xpath that uses `origination[@label='creator']` as the hook. This seems too flimsy a hook given no controlled vocabulary for the label attribute.

Examples in our [Traject config](https://github.com/projectblacklight/arclight/blob/master/lib/arclight/traject/ead2_config.rb): `/ead/archdesc/did/origination[@label='creator']` & `./did/origination[@label='creator']`. 

Broken example in Arclight Demo (Indiana using `@label='Creator'` with capital C):
[Component UI](https://arclight-demo.projectblacklight.org/catalog/VAB9846VAB9846-00036) vs. [Component EAD](https://github.com/sul-dlss/arclight-demo/blob/7ea05c3c440de6becfe49b88dd364b4c48080742/data/ead/InU-aaamc/VAB9846.xml#L1720-L1725) 

Note the LoC examples for origination use `<origination label="Creator:">`:
https://www.loc.gov/ead/tglib/elements/origination.html

What then is the ideal hook for this field? A case-insensitive regex including the word "creator"? Something else?

**Comment by noahgh221** [comment]
@seanaery , it might be sufficient just to index any text content of `<origination>` as the creator and ignore the label attribute altogether. The label attribute is optional and `<origination>`, at least according to the EAD Tag Library, should only be used to note the "individual or organization responsible for the creation, accumulation, or assembly of the described materials".

https://www.loc.gov/ead/tglib/elements/origination.html

**Comment by cmkpowell** [comment]
I agree.  This looks like the general practice across all the finding aids we host, regardless of who is creating them or how.
