### ISSUE TITLE
Top-level <dao>s are ignored

### ISSUE THREAD

**Issue by seanaery** [projectblacklight/arclight#789]
Currently, a `<dao>` at the top-level is ignored by our indexing and won't display a digital object in the UI. It is [permissible in EAD](https://www.loc.gov/ead/tglib/elements/dao.html) to have `<dao>s` at the top level as a child of `<archdesc>`. There is one such case in our fixtures, in `large-components-list.xml`.

**Comment by cbeer** [comment]
Is the top level DAO in `large-components-list.xml` correctly nested? It seems like the `<dao>` should be nested inside the `<archdesc>` `<did>`?
