### ISSUE TITLE
Update the "Group by collection" search results button

### ISSUE THREAD

**Issue by ggeisler** [projectblacklight/arclight#793]
The goal is to change the current "Group by collection" button, which acts as a toggle to switch between the default and grouped view of search results, to a button menu (button group in Bootstrap terms, I think) with the two options always visible, and the active option highlighted:

<img width="867" alt="Screen Shot 2019-09-11 at 4 32 46 PM" src="https://user-images.githubusercontent.com/101482/64996969-3a840200-d894-11e9-9df5-25f392dbbff6.png">

So this button menu should look and behave very similar to the button group used for the list and compact view of results.

The complicated part is how to adjust things for different breakpoints (and I hope it's only the xsmall and small breakpoints that require extra work). The screenshots in the remainder of this ticket are based on the example code below for the search result button area. I'm not suggesting this is necessarily the exact code that should be used, but that's what I used for the screenshots so hopefully it will be helpful as at least a starting point.

- Added a new `<div>` to enclose all the button-related stuff (first and last rows of the example)
- Wrapped the new button menu in the `result-type-group` div (second row of the example)

```
<div>
  <div class="result-type-group btn-group float-lg-left float-md-right">
    <a class="btn btn-outline-secondary active" href="/catalog?group=true&amp;q=&amp;search_field=all_fields">All results</a>
    <a class="btn btn-outline-secondary " href="/catalog?group=true&amp;q=&amp;search_field=all_fields">Grouped by collection</a>
  </div>

  <div class="search-widgets float-md-right">

  <div id="sort-dropdown" class="sort-dropdown btn-group">
  <button type="button" class="btn btn-outline-secondary dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
      Sort <span class="caret"></span>
  </button>
...
</div>
```

### Default (xsmall) breakpoint

- [x] The "All results | Group by collection" button menu should display in a row of its own, above the other search result buttons
- [x] The "All results | Group by collection" button menu should be left-aligned, as the other button row is at this breakpoint

- [x] The button rows should have spacing between them (~10px)

- [ ] The label for the "Sort by relevance" button should be shortened to read "Sort"
- [ ] The label for the "10 per page" button should be shortened to read "10" (or whatever the current selection is)

If I recall correctly, @jvine would like to see both rows of buttons collapsed by default at this and  the `small` breakpoints. In the interests of getting the main goal of this ticket done more quickly, I'll create another ticket to cover the collapse goal, but if the person working on this thinks it will be easier to add the collapse behavior at the same time, the goal is to have a collapse button (like the facet collapse button next to the "Limit your search" heading in the screenshot below) below the pagination info that toggles the display of the two rows of search result buttons.

Result should look like this:

<img width="296" alt="Screen Shot 2019-09-11 at 4 45 35 PM" src="https://user-images.githubusercontent.com/101482/64987062-40221d80-d87d-11e9-86a1-f2e4138af739.png">

---

### small breakpoint

At the small breakpoint we still don't have enough width to display all the buttons on the same row, but we do have more width so:

- [x] Use the full label for the "Sort by relevance" button
- [x] Use the full label for the ""10 per page" button

I don't think anything else changes at `small`. Result should look like this:

<img width="558" alt="Screen Shot 2019-09-11 at 4 42 59 PM" src="https://user-images.githubusercontent.com/101482/64989699-e91f4700-d882-11e9-8ddb-aca3e653aa2f.png">

---

### medium breakpoint

At the medium breakpoint the "Sort by" and other default buttons float to the right. In the screenshot below (and in the example code above) I'm suggesting that we do the same with the "All results | Group by" button menu. However, if we can get this ticket taken care of in Blacklight: https://github.com/projectblacklight/blacklight/issues/2133, the medium breakpoint will have a full-width main content area (like the large and xlarge breakpoints) so the buttons will all fit in the same row.

So if we can do https://github.com/projectblacklight/blacklight/issues/2133, we can edit this line:

`<div class="result-type-group btn-group float-lg-left float-md-right">`

to remove `float-md-right` and change `float-lg-left` to `float-md-left`

I don't think anything else needs to be done for the medium and above breakpoints. 

If we don't do https://github.com/projectblacklight/blacklight/issues/2133, then we need to keep the `float-lg-left float-md-right` classes on the `result-type-group` div and the result should look like this:

<img width="662" alt="Screen Shot 2019-09-11 at 4 41 17 PM" src="https://user-images.githubusercontent.com/101482/64992011-df4c1280-d887-11e9-85a0-209b8ef5f11c.png">

---

### large breakpoint
At the `large` breakpoint there should be sufficient space to hold all the buttons on one line. The "Group by collection" button group should be left-aligned, while the other buttons should continue to be right-aligned, like this:

<img width="726" alt="Screen Shot 2019-09-11 at 4 35 08 PM" src="https://user-images.githubusercontent.com/101482/64992000-d8bd9b00-d887-11e9-9c66-ef6319cf60f8.png">

---

### xlarge breakpoint
No change from `large`, just provides additional space between the left- and right-aligned buttons:

<img width="867" alt="Screen Shot 2019-09-11 at 4 32 46 PM" src="https://user-images.githubusercontent.com/101482/64991992-d3605080-d887-11e9-933f-26e58286f985.png">

**Comment by jkeck** [comment]
A couple notes/possible spin off tickets:
* I used `spacing * 0.5` (which gives us `0.5rem`).
* WRT dropping the labels of the sort and per page drop downs in a responsive manner, this will most likely require changes upstream in Blacklight.  Given that the responsiveness works w/o dropping those labels down further, perhaps that can be spun off into a separate issue.

**Comment by camillevilla** [comment]
Also want to make sure that the label-switching on these buttons works in a screenreader-friendly way. I've split this out to #804.
