### ISSUE TITLE
Add icons to collection/component show page breadcrumbs

### ISSUE THREAD

**Issue by ggeisler** [projectblacklight/arclight#801]
Related to #796, and I think it will be more straightforward if that ticket is considered a prerequisite for this one.

At the bottom of this ticket is a table with the four icons that are relevant to displaying the breadcrumbs on the collection and component show pages. The logic for assigning the icons to the breadcrumb hierarchy is:

- [ ] Use the `repository` icon for the repository name breadcrumb
- [ ] Use the `collection` icon for the collection name breadcrumb
- [ ] If the current show page is for a file-level item, use the `file` icon for the `h1.breadcrumb-item`
- [ ] If the current show page is for a container item (an item below the collection but not a file-level item), use the `folder` icon for the `h1.breadcrumb-item`
- [ ] If the current show page has any containers below the collection-level and above the current item, use the `folder` icon for the breadcrumb of those intermediate levels

Here's an example of how the breadcrumb icons look with the above logic (this example has only one container-level breadcrumb, but note that there can be multiple container breadcrumbs -- if there were one or more subseries, for example):

<img width="693" alt="Screen Shot 2019-09-17 at 1 13 00 PM" src="https://user-images.githubusercontent.com/101482/65076000-e721ba80-d94c-11e9-90b9-414a9e3573d7.png">

### Complications
For the screenshot above I added the icon svgs directly in the `_show_breadcrumbs_default.html.erb` file. However, that might not be the ideal way of including the icons, because with that approach the icon is part of the text element and thus if the text wraps, it wraps such that the second line is left-aligned with the left edge of the icon, rather than the left edge of the text:

<img width="693" alt="Screen Shot 2019-09-17 at 1 13 00 PM" src="https://user-images.githubusercontent.com/101482/65076652-47652c00-d94e-11e9-9cab-d9c67dedcd99.png">

We want it to look like this:

<img width="693" alt="Screen Shot 2019-09-17 at 1 26 38 PM" src="https://user-images.githubusercontent.com/101482/65076947-cfe3cc80-d94e-11e9-98c0-5f21e57a373e.png">

And the same with any higher-level breadcrumbs that wrap.

I think a solution might be to use the `list-style-image` CSS property, with the icons specified as a background image for the list item bullet/number. I didn't try this approach myself, but if we can display the breadcrumb icons this way, the text wrapping should work as we want, since the icons are now effectively the list item bullets rather than part of the list item text itself.

Another solution might be using the `margin-left` CSS property with both positive and negative values, as I noted in the "Implementation hints" section of #829.

### Styling adjustments
We'll probably want to make some styling adjustments after the icons have replaced the current `»` (I needed a handful to get what you see in the screenshot). It'll probably be more efficient to deal with fine-tuning the styling after we get the basic solution in place, and I'm happy to work on that myself later, but one relevant adjustment I made was to increase the indent of each breadcrumb to `15px` from `10px` in `layout.scss`. And I used `fill: $gray-600;` for the icon color.

### Icons
Note that the repository icon is from Material.io and needs no attribution. The others do, but we're already using them for the search result items so I assume the attribution stuff is already in place for those.

Icon | Source | SVG code
------------ | ----------| -------------
repository | Material.io [[account_balance](https://material.io/resources/icons/?search=accoun&icon=account_balance&style=sharp)] | `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path fill="none" d="M0 0h24v24H0V0z"/><path d="M4 10v7h3v-7H4zm6 0v7h3v-7h-3zM2 22h19v-3H2v3zm14-12v7h3v-7h-3zm-4.5-9L2 6v2h19V6l-9.5-5z"/></svg>`
collection | Font Awesome [[archive](https://fontawesome.com/icons/archive?style=solid) ] | `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><path d="M32 448c0 17.7 14.3 32 32 32h384c17.7 0 32-14.3 32-32V160H32v288zm160-212c0-6.6 5.4-12 12-12h104c6.6 0 12 5.4 12 12v8c0 6.6-5.4 12-12 12H204c-6.6 0-12-5.4-12-12v-8zM480 32H32C14.3 32 0 46.3 0 64v48c0 8.8 7.2 16 16 16h480c8.8 0 16-7.2 16-16V64c0-17.7-14.3-32-32-32z"/></svg>`
container | Font Awesome [[folder](https://fontawesome.com/icons/folder?style=solid)] | `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><path d="M464 128H272l-64-64H48C21.49 64 0 85.49 0 112v288c0 26.51 21.49 48 48 48h416c26.51 0 48-21.49 48-48V176c0-26.51-21.49-48-48-48z"/></svg>`
file | Font Awesome [[file](https://fontawesome.com/icons/file?style=solid)] | `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 384 512"><path d="M224 136V0H24C10.7 0 0 10.7 0 24v464c0 13.3 10.7 24 24 24h336c13.3 0 24-10.7 24-24V160H248c-13.2 0-24-10.8-24-24zm160-14.1v6.1H256V0h6.1c6.4 0 12.5 2.5 17 7l97.9 98c4.5 4.5 7 10.6 7 16.9z"/></svg>`

**Comment by anarchivist** [comment]
Closes #193

**Comment by anarchivist** [comment]
Closes #193.
