### ISSUE TITLE
Add component context/actions box to collection show page

### ISSUE THREAD

**Issue by camillevilla** [projectblacklight/arclight#805]
Descends from #631. Most of this was implemented in #695 for component show pages, so this ticket should hopefully be able to reuse the partial implemented there or refactor it to make it more generic (maybe using the `collection_unitid` implemented in #750?) 

<img width="1143" alt="Screen Shot 2019-08-26 at 11 55 52 AM" src="https://user-images.githubusercontent.com/101482/63716048-f43e0480-c7f9-11e9-972b-a9ff32cd62c2.png">

See case A:
<img width="1027" alt="Screen Shot 2019-08-26 at 12 11 09 PM" src="https://user-images.githubusercontent.com/101482/63716540-1be19c80-c7fb-11e9-9773-4c2ca4dfd60a.png">

**Comment by mejackreed** [comment]
This seems to be resolved now in `master`
