### ISSUE TITLE
Update display of current component and siblings in collection context

### ISSUE THREAD

**Issue by camillevilla** [projectblacklight/arclight#811]
Split out of #670 / #673

   - [x] Current component is highlighted with a yellow background (1, below)
   - [x] Because the current component may be far down in the tree, portions of the tree are hidden to ensure the current component is visible in the tab. 
   - [x] The entire remaining tree _below_ the current component is shown. 

![](https://user-images.githubusercontent.com/6945691/63970094-29479280-ca58-11e9-96d0-adbffe79733b.png)

**Comment by mejackreed** [comment]
Resolved in #889 (as far as I can tell). Please open a new issue for a missing piece of this. cc @jrgriffiniii
