### ISSUE TITLE
Collection context tree: open collapsed sections by clicking Expand button

### ISSUE THREAD

**Issue by camillevilla** [projectblacklight/arclight#813]
Split out of #668 / #673
Depends on #811 and maybe #812

- [ ] **Open collapsed sections by clicking Expand**
   - When the user clicks an Expand button, insert the hidden portion of the tree into that space, and remove the Expand button (there's no parallel Collapse behaviour). Expand (2) inserts all the siblings above the current one. Expand (3) inserts the remainder of the tree above the immediate parent. [Interactive mockup of this behaviour](https://xd.adobe.com/view/fe3abb57-312c-4393-6031-b3da9dba7023-880b/).

<img width="1123" alt="current componetnt in tree" src="https://user-images.githubusercontent.com/6945691/63970094-29479280-ca58-11e9-96d0-adbffe79733b.png">

**Comment by mejackreed** [comment]
Resolved previously by @jrgriffiniii
