### ISSUE TITLE
Add repository/container icon to search result item breadcrumbs

### ISSUE THREAD

**Issue by ggeisler** [projectblacklight/arclight#829]
This applies to:

- List view and compact view of **flat search results**, using the repository icon
- List view and compact view of **grouped search results**, using the folder icon

Goals are:

- [x] Prepend a repository/container icon to the breadcrumb line in search result items

- [x] Ensure that when the breadcrumb line wraps, subsequent lines are left-aligned with the first line text, rather than the left-edge of the icon

### Example in desktop viewport
<img width="705" alt="Screen Shot 2019-09-18 at 2 45 14 PM" src="https://user-images.githubusercontent.com/101482/65188857-32f36300-da24-11e9-9146-5e6eb01e0bb3.png">

### Example in mobile viewport

<img width="389" alt="Screen Shot 2019-09-18 at 2 52 55 PM" src="https://user-images.githubusercontent.com/101482/65188866-37b81700-da24-11e9-9143-c447dbd2fd6f.png">

### Icons
For the non-grouped result views, this [Material icon](https://material.io/resources/icons/?search=accoun&icon=account_balance&style=sharp) (no attribution needed) is the one to use as the repository icon.

For the grouped results, we start the breadcrumb at a container level, so we need to use the container (folder) icon we're already using elsewhere in the app.

### Implementation hints
Here's how I implemented the solution shown in the screenshots (basically adding the `margin-left` properties). I'm not suggesting this is the best way to do this (are there drawbacks to using negative margins like this?). It seems to work but maybe there are better ways?

```
.breadcrumb-links.col {
    margin-left: 20px;
}

.breadcrumb-links.col svg {
    height: 1rem;
    width: 1rem;
    fill: #6c757d;
    margin-left: -20px;
}
```

(I also added vertical spacing between the scope note and the breadcrumb line, but I believe that will be taken care of in #826.)

**Comment by gordonleacock** [comment]
In the views/shared/_show_breadcrumbs.html.erb we used media and media-body bootstrap classes which neatly handle the issue of text wrapping under the icon. See https://getbootstrap.com/docs/4.0/layout/media-object/#example

**Comment by ggeisler** [comment]
Nice @gordonleacock. Glad there is a nice way of handling that!
