### ISSUE TITLE
Figure out why es6 isn't working in #856

### ISSUE THREAD

**Issue by mejackreed** [projectblacklight/arclight#869]
Implemented some new JavaScript in #856 but it doesn't seem to be going through sprockets correctly.

https://github.com/projectblacklight/arclight/pull/856#discussion_r326716182

**Comment by jrgriffiniii** [comment]
This seems to be somehow related to the Babel presets which are being passed to `sprockets-bumble_d` in https://github.com/rmacklin/sprockets-bumble_d/blob/master/lib/sprockets/bumble_d/transformer.rb#L44

**Comment by jrgriffiniii** [comment]
https://github.com/projectblacklight/arclight/compare/babel-helpers demonstrates that ES6 *does* work when I attempt to integrate Babel support for decorators.  Removing https://github.com/projectblacklight/arclight/compare/babel-helpers#diff-59e3030a8297d96d94f517dcf1f90f28R26 will trigger breakage in the browser, while it does provide a simple `@readonly` decorator in the ES6 Class `Foo`:
https://github.com/projectblacklight/arclight/compare/babel-helpers#diff-1f8d1d46ba0566faba522da15f971bccR7

**Comment by seanaery** [comment]
Resolving this issue as part of a review of `arclight 1.0.x`. v1 no longer uses `babel` nor `sprockets_bumble_d` and the remaining ES6 appears to work properly.
