### ISSUE TITLE
Update bookmark icons to be decorative icons

### ISSUE THREAD

**Issue by labradford** [projectblacklight/arclight#876]
If Blacklight icons are updated per issue https://github.com/projectblacklight/blacklight/issues/2150, convert the bookmark icons to be BlackLight decorative icons

References https://github.com/projectblacklight/arclight/pull/873 and https://github.com/projectblacklight/arclight/issues/862

**Comment by seanaery** [comment]
Resolving this issue as part of a review of `arclight 1.0.x`.
