### ISSUE TITLE
Collection context: ways to make JS more explicit or maintainable

### ISSUE THREAD

**Issue by mejackreed** [projectblacklight/arclight#897]
The `updateView` method is starting to get a little gnarly. This ticket aims to either:
 - document a proposal for modifying to enable maintainability
 - implement the proposal

https://github.com/projectblacklight/arclight/blob/master/app/assets/javascripts/arclight/context_navigation.js#L58-L147

**Comment by jrgriffiniii** [comment]
Might it be an improvement to restructure `static` methods as separate Classes?  https://github.com/projectblacklight/arclight/blob/master/app/assets/javascripts/arclight/context_navigation.js#L30 leads me to believe that one alternative might be to offer something similar to the following:

```javascript
class HierarchyPlaceholder {
[...]
  constructor() {
    this.el = $('<div class="al-hierarchy-placeholder">[...]</div>');
  }
[...]
  render() {
    this.el.html();
  }
}
```

**Comment by mejackreed** [comment]
That could work. I was wondering about the static methods themselves and why you went w/ static as opposed to instance methods?

**Comment by jrgriffiniii** [comment]
It felt more consistent to start offering static methods once working within the scope of `onClick` callbacks.  I could try and bind the `onClick` callbacks consistently to `this` within the scope of each Class, and then restructure many of the static methods into instance methods.

Also, there were warnings issued from ESLint regarding the implementation of instance methods which did not contain `this`.  I can override these if that would be acceptable.

**Comment by jrgriffiniii** [comment]
I've made progress with this on https://github.com/projectblacklight/arclight/compare/issues-897-jrgriffiniii-collection-js-restructure, as well as having fixed a bug.

**Comment by jrgriffiniii** [comment]
https://github.com/projectblacklight/arclight/compare/issues-897-jrgriffiniii-collection-js-restructure gets things farther, but I haven't quite fully tested this.  I would also like to use this as a basis for looking to address https://github.com/projectblacklight/arclight/issues/925.

**Comment by mejackreed** [comment]
Gotcha. Could we separate the collection navigation changes out? I think that might go away if we get this wrapped up nicely. That might make it cleaner to move forward?

**Comment by mejackreed** [comment]
I'm going to close this as much of this has been addressed. Thanks for the great work.
