### ISSUE TITLE
Several EAD elements still need indexing, display, and/or formatting

### ISSUE THREAD

**Issue by seanaery** [projectblacklight/arclight#898]
There are several EAD2002 elements for which we still need to make revisions to ensure they are indexed, displayed, and formatted correctly. I have assembled a list below using other platforms' rendering rules as a guide ([e.g., this file](https://github.com/archivesspace/archivesspace/blob/master/stylesheets/as-ead-html.xsl)) though this list still may not be exhaustive.

 See also #761 , #758 , #760 which include additional elements for formatting.

 Element Still Needs: | Indexing | Display | Formatting  
 ---- | ---- | ---- | ----
[index](http://eadiva.com/2/index/) / [indexentry](https://www.loc.gov/ead/tglib/elements/indexentry.html) | X | X | X
[daogrp](https://www.loc.gov/ead/tglib/elements/daogrp.html) | X | X | X
[address](https://www.loc.gov/ead/tglib/elements/address.html) | X | X | X
[revisiondesc](https://www.loc.gov/ead/tglib/elements/revisiondesc.html) | X | X | X
[filedesc](https://www.loc.gov/ead/tglib/elements/filedesc.html) / ( [titlestmt](https://www.loc.gov/ead/tglib/elements/titlestmt.html), [editionstmt](https://www.loc.gov/ead/tglib/elements/editionstmt.html), [notestmt](https://www.loc.gov/ead/tglib/elements/notestmt.html), [publicationstmt](https://www.loc.gov/ead/tglib/elements/publicationstmt.html), [seriesstmt](https://www.loc.gov/ead/tglib/elements/seriesstmt.html) ) | X | X | X
[bibliography](https://www.loc.gov/ead/tglib/elements/bibliography.html) | | X | X
[fileplan](https://www.loc.gov/ead/tglib/elements/fileplan.html) | | X | X
[odd](https://www.loc.gov/ead/tglib/elements/odd.html) | | X | 
[otherfindaid](https://www.loc.gov/ead/tglib/elements/otherfindaid.html) | | | X
[table](https://www.loc.gov/ead/tglib/elements/table.html) | | | X
[archref](https://www.loc.gov/ead/tglib/elements/archref.html) | | | X
[legalstatus](https://www.loc.gov/ead/tglib/elements/legalstatus.html) | | | X
[ref links](https://www.loc.gov/ead/tglib/elements/ref.html) | | | X
[ptr links](https://www.loc.gov/ead/tglib/elements/ptr.html) | | | X
[extref links](https://www.loc.gov/ead/tglib/elements/extref.html) | | | X
[extptr links](https://www.loc.gov/ead/tglib/elements/extptr.html) | | | X
[linkgrp](https://www.loc.gov/ead/tglib/elements/linkgrp.html) | | | X
[blockquote](https://www.loc.gov/ead/tglib/elements/blockquote.html) | | | X
[lb](https://www.loc.gov/ead/tglib/elements/lb.html) | | | X

CC: @anarchivist

**Comment by jlhardes** [comment]
Adding the following elements to list not displaying:

Within physdesc:
[physfacet](https://www.loc.gov/ead/tglib/elements/physfacet.html)
[dimensions](https://www.loc.gov/ead/tglib/elements/dimensions.html)

Provenance info:
[custodhist](https://www.loc.gov/ead/tglib/elements/custodhist.html)

Collection processing info:
[processinfo](https://www.loc.gov/ead/tglib/elements/processinfo.html)

I don't think any of these need to be indexed for searching/browsing.

**Comment by jlhardes** [comment]
Within components (c0x), we're finding that some elements are not displaying:

[language](https://www.loc.gov/ead/tglib/elements/language.html)
[accessrestrict](https://www.loc.gov/ead/tglib/elements/accessrestrict.html)

These seem to be displaying at the collection level but not when they are included in a component.

**Comment by brijmcla** [comment]
In addition to the collection level notes mentioned, we're finding that these elements are not displaying:
[materialspec](https://www.loc.gov/ead/tglib/elements/materialspec.html)

In addition to the c0x level notes mentioned, we're finding that these elements are not displaying:
[bioghist](https://www.loc.gov/ead/tglib/elements/bioghist.html)
[originalsloc](https://www.loc.gov/ead/tglib/elements/originalsloc.html)
[relatedmaterial](https://www.loc.gov/ead/tglib/elements/relatedmaterial.html)
[separatedmaterial](https://www.loc.gov/ead/tglib/elements/separatedmaterial.html)
[materialspec](https://www.loc.gov/ead/tglib/elements/materialspec.html)

**Comment by dinahhandel** [comment]
- Needs more discussion as to which elements are required to display, might need to be broken down to be workable. 
- Product owners should huddle and prioritize, provide input on formatting when relevant. 
- Should also separate out component-level display requests from collection level requests. 
- Draft statement of what ArcLight supports (what displays at the collection level should display at the component level).

**Comment by seanaery** [comment]
At the conclusion of the [Dec 2023 Community Sprint 3](https://github.com/orgs/projectblacklight/projects/3/views/2), I have reviewed this ticket closely. The ticket was deemed `blocked` at the start of the sprint because it was too complex to be actionable. However, the team broke out smaller, discrete tickets from here and addressed almost all of them during the sprint.

All of the elements mentioned in this ticket description and in the discussion threads are now accounted for in other tickets, most of which have been closed.

Thus, I will close out this ticket.

**DONE**
- `index` / `indexentry` #1453
- `fileplan` #1459
- `odd` #1456
- `otherfindaid` #1460
- `table` #1494
- `ref`, `ptr`, `extref`, `extptr` #1449
- `address`, `blockquote` (shown to render OK via #990)
- `lb` #1457
- `physfacet` #1448
- `dimensions` #1448
- `custodhist` #898
- `processinfo` #1463
- `materialspec` #1451
- `bioghist` #1452
- `originalsloc`, `relatedmaterial`, `separatedmaterial` #1464
- `altformavail` #1450

**TICKETED / TO DO**
- `daogrp` #1016
- `revisiondesc` #1454
- `filedesc` (`titestmt`, `editionstmt`, `notestmt`, `publicationstmt`, `seriesstmt`) #1455
- `archref` #1461
- `linkgrp` #1507
- `language` #1508
- `bibliography` / `bibref` #1458
