### ISSUE TITLE
Grouped by collection results take a long time to load

### ISSUE THREAD

**Issue by noahgh221** [projectblacklight/arclight#920]
Grouped by results seem to take a long time to load either when initiating searches in grouped-by collection mode or when toggling from "all results" to "grouped by collection."

A few example queries:
"North Carolina" - 9 seconds
"Kentucky" - 20 seconds

**Comment by seanaery** [comment]
Resolving this issue as part of a review of `arclight 1.0.x`. This no longer seems to be happening.
