### ISSUE TITLE
Style conflicts causing indention issues in collection context

### ISSUE THREAD

**Issue by mejackreed** [projectblacklight/arclight#925]
https://arclight-demo.projectblacklight.org/catalog/ARS-0046aspace_ref37_is2

![Screen Shot 2019-10-08 at 10 56 52 AM](https://user-images.githubusercontent.com/1656824/66416105-5c1b6980-e9ba-11e9-8ef5-223c13c5c36d.png)

**Comment by labradford** [comment]
@jrgriffiniii I think I know how to fix this styling to fix the weird nested wrapping. Are you actively working on the style fixes for this ticket?

**Comment by labradford** [comment]
I'm going to go ahead and put up a PR just in case you were working more on the JS side of this issue.

**Comment by jrgriffiniii** [comment]
Sorry, I was not, I will review #932.

**Comment by jrgriffiniii** [comment]
https://github.com/projectblacklight/arclight/compare/issues-897-jrgriffiniii-collection-js-restructure#diff-420333906b23e241c8ec41ea7665f017R160 was also a small bug which I've found, but this is unrelated to the styling.

**Comment by jrgriffiniii** [comment]
https://github.com/projectblacklight/arclight/pull/932 closed much of this (thank you very much @labradford for addressing this), I'm going to try and find anything further problematic.

**Comment by jrgriffiniii** [comment]
As I'm not finding any more undesirable element placements or alignments, I'm going to consider this closed.
