### ISSUE TITLE
Collection context expansion CSS transitions should produce identical behavior to .al-toggle-view-all

### ISSUE THREAD

**Issue by jrgriffiniii** [projectblacklight/arclight#933]
I personally much prefer the transitions available for +/- buttons rendered at the collection-level "Contents" interface: http://localhost:3000/catalog/2000C3-xml, and would like to port this to the "Expand"/"Collapse" behavior for components: http://localhost:3000/catalog/2000C3-xmlref75

**Comment by seanaery** [comment]
Resolving this issue as part of a review of `arclight 1.0.x`. Given the layout changes in v1 the `+/-` buttons are consistent whether at a collection or component level.
