### ISSUE TITLE
Remove or fix "Grouped by collection" view of Bookmarks

### ISSUE THREAD

**Issue by ggeisler** [projectblacklight/arclight#942]
When you go to your Bookmarks page in ArcLight, things mostly look good. However, it looks like we're inheriting the "Grouped by collection" option for viewing the bookmarks and it doesn't seem to work in the bookmarks context. When I select it, I am just redirected to the application homepage.

<img width="962" alt="Screen Shot 2019-10-11 at 9 35 35 AM" src="https://user-images.githubusercontent.com/101482/66668850-08538f00-ec0b-11e9-947c-65ce929576d5.png">

I think the "Grouped by collection" option could have value in the bookmark list context but I'm not sure if we can do it without creating a bookmark-specific view of the grouped results. That is, if we just use the standard grouped by result view, where we list the top 3 hits under each collection, what would happen if a given collection has more than 3 bookmarks and the user selected "View all x" for that collection? It seems like we'd have to do a fair amount of customization to have a useful way for the user to navigate between what would effectively be a collection-faceted view of bookmarks and back to the full list of bookmarks.

Alternatively, we could remove the "Grouped by collection" option, but add a "sort by collection" option to the sort dropdown. So the bookmarks results are still just one flat list but at least sorted by collection.

Less helpful to the user but probably the easiest fix is to simply hide the "Grouped by collection" option on the Bookmark results page. (And if we do that I guess what we really do is hide the whole menu button with the "All results | Grouped by collection" options, since without the Grouped choice the other choice is the only choice.)

I don't have a good sense of how the Bookmarks page is generated and inherits the search result views so I'm just presenting possible solutions here, without a strong opinion on which option is best in terms of the development effort/user benefit tradeoff.

**Comment by camillevilla** [comment]
@ggeisler I took a quick look at this and it is possible to remove the toggle for the bookmarks view. We're left with this weird gap from the `results_pagination` which is defined as a `col-md-12` upstream in Blacklight. Does this look ok or would you like me to try and conditionally left align the rest of the sort and per page options? 

![Screen Shot 2019-10-14 at 4 19 42 PM](https://user-images.githubusercontent.com/5402927/66789034-b4f96f00-ee9e-11e9-8ad6-62d97d965b2d.png)

**Comment by ggeisler** [comment]
@camillevilla I see. It looks like there's this wrapping `<div>` that makes the `.page-links` div extend full-width (see the blue highlighted line below):

<img width="582" alt="Screen Shot 2019-10-14 at 4 51 23 PM" src="https://user-images.githubusercontent.com/101482/66790073-25a28a80-eea3-11e9-965b-11bc77450a96.png">

Do you see a way where that wrapping div could be removed? If I remove it in Web inspector, after removing the div with the grouped menu option, everything ends up in one row, which is the ideal result:

<img width="952" alt="Screen Shot 2019-10-14 at 4 55 27 PM" src="https://user-images.githubusercontent.com/101482/66790146-7619e800-eea3-11e9-856e-86152c93e75e.png">

If that can't be done for reason, I'd just leave it as is; I think it might be better overall to be consistent with the right-aligned placement of the search result controls.
