### ISSUE TITLE
Validate validity and structure of expando semantic markup and fix

### ISSUE THREAD

**Issue by mejackreed** [projectblacklight/arclight#962]
The current "Expand/Collapse" button used in contextual navigation presents likely semantic HTML validation issues.

It presents a `<ul>` with a direct child that is another `<ul>`.

[Screen Shot 2019-10-18 at 1 59 48 PM](https://user-images.githubusercontent.com/1656824/67124375-a4533c80-f1af-11e9-841b-aa7f87a56742.png)

### Acceptance criteria

- [ ] Accomplish the same user experience using valid HTML

While it might be useful to have #957 🚢 first, I could see a solution working without needing that.

**Comment by seanaery** [comment]
Resolving this issue as part of a review of `arclight 1.0.x`. The new context tree nav in v1 has valid markup.
