### ISSUE TITLE
Review online content for specific record

### ISSUE THREAD

**Issue by mejackreed** [projectblacklight/arclight#974]
See: https://arclight-demo.projectblacklight.org/catalog/VAD1751VAD1751-00175

Fix was supposed to be in https://github.com/projectblacklight/arclight/pull/971

**Comment by seanaery** [comment]
Resolving this issue as part of a review of `arclight 1.0.x`. Online content links and indicators appear to be functioning as intended whether directly present on a collection/component or present in a descendant component.
