### ISSUE TITLE
Breadcrumb for items in Online content tab needs updating

### ISSUE THREAD

**Issue by ggeisler** [projectblacklight/arclight#976]
Similar issue to #977. The breadcrumb used for items in the Online content tab follows the same structure as the breadcrumb used for search result items, which is the repository icon, followed by the complete collection path to the item, starting at the repository level.

<img width="961" alt="Screen Shot 2019-10-25 at 4 43 21 PM" src="https://user-images.githubusercontent.com/101482/67610359-03ccc180-f747-11e9-8149-64d6d3a65530.png">

This is not how we want to structure the breadcrumb for items in the Online content tab. In that context, all items belong to the same collection, so displaying the repository and collection is unnecessary. Instead, we'd like to start the breadcrumb path with the top-most ancestor of the item and follow that with the path to the item. See this mockup that was part of #679 for some examples:

<img width="998" alt="63986696-ef8f7f80-ca89-11e9-8715-8127cca853b0" src="https://user-images.githubusercontent.com/101482/67610416-85245400-f747-11e9-8367-778d364e74c9.png">

Note that this mockup doesn't have an example of the case where an item is at the series level, where its immediate parent is the collection. In that case, I think we should omit the breadcrumb entirely for the item, since that's the only way we can be consistent about not showing the collection name as part of the breadcrumb in this context.

**Comment by seanaery** [comment]
Resolving this issue as part of a review of `arclight 1.0.x`. The online content tab is no longer in the layout.
