### ISSUE TITLE
Collection Context expand/collapse bug - same components appear as children of different parents

### ISSUE THREAD

**Issue by noahgh221** [projectblacklight/arclight#982]
If I am viewing a component page in the demo app ([example](https://arclight-demo.projectblacklight.org/catalog/umich-bhl-2013066aspace_9c83b47189c612469bdf7d4ccb124835)), when I click the plus icon to expand other nearby parent components, I see the same child components listed under every parent (with the current component duplicated and highlighted in yellow multiple times).

Here's a screenshot that better illustrates the problem:

![image](https://user-images.githubusercontent.com/7328518/67978842-61eb2000-fbf1-11e9-899b-cd4057b6dc99.png)

**Comment by anarchivist** [comment]
Colleagues at IU provided a video demonstrating this issue: https://iu.app.box.com/s/pqjeimei67fzhh4imchm68q1o2itch7n

**Comment by seanaery** [comment]
Hi @anarchivist -- I have developed a fix for this issue in our local (Duke) ArcLight implementation. Here are the code changes it required (all contained to `context_navigation.js`):
https://gitlab.oit.duke.edu/dul-its/dul-arclight/-/merge_requests/36/diffs

I plan to prepare a similar ArcLight PR later today for consideration; hopefully this'll be a solution everyone can use.
