### ISSUE TITLE
Collection contents tree is not displaying children for Stanford finding aids

### ISSUE THREAD

**Issue by anarchivist** [projectblacklight/arclight#984]
E.g. [Zimbardo](https://arclight-demo.projectblacklight.org/catalog/sc0750-xml): 

![Zimbardo](https://user-images.githubusercontent.com/73732/68156741-5ca41300-ff1a-11e9-86ec-75297cea172e.gif)

**Comment by archivalGrysbok** [comment]
Did you figure out what causes this?  
I'm also seeing this with some of my finding aids 
(Example:  http://archives.library.wcsu.edu/caoSearch/catalog/beinecke-ycalmiscellanyref11 ).

**Comment by seanaery** [comment]
@anarchivist , @archivalGrysbok  -- Looks like this is only happening in cases where the collection's `<eadid>` has a dot in it. I think this will be an easy fix; there's an existing helper method to change the `.` to a `-` that just isn't currently getting applied to the id in this section. I will plan to issue a PR today to fix it.
