### ISSUE TITLE
Indexing errors when fields exceed byte limits

### ISSUE THREAD

**Issue by noahgh221** [projectblacklight/arclight#992]
In local Arclight testing, we encountered two cases where EADs failed to index:

`<bioghist>` exceeds 32,766 byte limit (indexed as string field)

`<accessrestrict>` exceeds 32,766 byte limit (indexed as string field)

We noticed these issues in only two of our ~4,000 EADs. It is unusual that these two fields would contain so much text, but not impossible.

**Comment by seanaery** [comment]
Resolving this issue as part of a review of `arclight 1.0.x`. This was fixed by #1355 .
