### ISSUE TITLE
When notes fields are 'too long', EAD is not indexed

### ISSUE THREAD

**Issue by archivalGrysbok** [projectblacklight/arclight#994]
I'm getting this error when indexing several EADs:

> DocValuesField "scopecontent_ssm" is too large, must be <= 32766

I've also see it for "odd_ssm". I'm still going through my "failed to index" list, but I expect to find other too-long fields. I've confirmed that these fields are actually long.

Could Arclight split, truncate, or otherwise munge too-long fields so that the EAD can be indexed?

**Comment by seanaery** [comment]
@archivalGrysbok We have noticed that recently at Duke as well. See #992 .

In our local implementation, we have changed any note-like fields (that can be reasonably expected to exceed 32766 bytes) from string fields to text. It involves changing the `_ssm` suffix to `_tesim`, changing any existing references to the fields in their `_ssm` form, and reindexing everything.
https://gitlab.oit.duke.edu/dul-its/dul-arclight/-/commit/98b4dcbe7a707f57db3fc9eed07e87b0d4d7ba4b

We also implemented a sort of compressor to get rid of any unneeded whitespace during the indexing process to help with byte limits in fields.
https://gitlab.oit.duke.edu/dul-its/dul-arclight/-/commit/7485a42ab9425fffc64ef0b6b457c51ab0f59381

I can propose those revisions as changes to the core software via a merge request for community consideration. We have had this change in place for a couple weeks in our instance and it seems to have adequately addressed the problem.

CC: @anarchivist
