### ISSUE TITLE
Contents display issues with IE and Edge

### ISSUE THREAD

**Issue by StevensBrian** [projectblacklight/arclight#995]
Viewing collection, contents in the contents tab do not load
https://arclight-demo.projectblacklight.org/catalog/umich-bhl-0234
![image](https://user-images.githubusercontent.com/380685/79763171-b2664f00-82f1-11ea-9851-6f432b713076.png)

Providing a url to one of this collection's components, brings you to the component but the contents and access tab contents do not render:
https://arclight-demo.projectblacklight.org/catalog/umich-bhl-0234aspace_6f110f3f57080da0686a137c19b40f4c

![image](https://user-images.githubusercontent.com/380685/79762915-5dc2d400-82f1-11ea-9a1b-aff30464e811.png)

**Comment by seanaery** [comment]
@StevensBrian It appears that the Edge issues are distinct from the IE issues, or, at least, a few minor javascript tweaks might get Edge working (since it supports ES6 syntax). The IE issues are more extensive/complex. I've created two separate tickets: #1010 and #1009

**Comment by jcoyne** [comment]
This was split into separate issues.
