### ISSUE TITLE
Allow display of multiple extents

### ISSUE THREAD

**Issue by eliotjordan** [projectblacklight/arclight#997]
We have a use case to display multiple collection-level extents. Proposal is to render badges for each extent value instead of plucking the first:

https://github.com/projectblacklight/arclight/blob/master/app/models/concerns/arclight/solr_document.rb#L57

![multi-extent](https://user-images.githubusercontent.com/784196/87350775-f5654680-c51d-11ea-9adb-3bfb4d3e8bf1.png)

**Comment by seanaery** [comment]
@eliotjordan We encountered this problem at Duke as well, so I second the desire to fix it in core. Rather than put each extent into its own badge, our solution (which may not be desired for everyone) was to concatenate / delimit them with a dash within one badge, then limit the max-width of the badge via CSS. A couple related changes we made to extent:
- Include all values from the physdesc field, not just extent
- Singularize values like "1 boxes" which appear frequently in ASpace exports
https://gitlab.oit.duke.edu/dul-its/dul-arclight/-/blob/develop/app/models/solr_document.rb#L95-104

**Comment by andyzyl321** [comment]
> @eliotjordan We encountered this problem at Duke as well, so I second the desire to fix it in core. Rather than put each extent into its own badge, our solution (which may not be desired for everyone) was to concatenate / delimit them with a dash within one badge, then limit the max-width of the badge via CSS. A couple related changes we made to extent:
> 
> * Include all values from the physdesc field, not just extent
> * Singularize values like "1 boxes" which appear frequently in ASpace exports
>   https://gitlab.oit.duke.edu/dul-its/dul-arclight/-/blob/develop/app/models/solr_document.rb#L95-104

@seanaery Hello Sean, I'm a student from Indiana University and currently working with <extent> problem on Arclight. Specifically, all <extent> values in collection/component level will be connected by comma, with an 'and' before the last value. For instance, the <physdesc> tag in xml file is showing up below:

<img width="1157" alt="Screen Shot 2020-08-10 at 9 59 03 AM" src="https://user-images.githubusercontent.com/44649202/89790774-6b92a400-daf0-11ea-8f06-245f526def68.png">

It is showing as this in Arclight: 
**3 cubic feet, One cubic-foot records case; one letter-size documents case; and twenty-six shelved books., and 4 CDs** 
The way we want it to show up is: 
**3 cubic feet (One cubic-foot records case; one letter-size documents case; and twenty-six shelved books. and 4 CDs)**
For each <physdesc>, there is only one top level physical description whose attribute is altrender="materialtype spaceoccupied", while all other <extent> with altrender="carrier" attribute are specific description and we want to included them in brackets. Moreover, the connection comma in front of the first '(' bracket and the last 'and' should be removed also.

I have tried to modify the ead2_config.rb file and add '(' right in front of the first <extent> value with attribute altrender="carrier" and ')' after the last value. However, I'm struggling in remove the comma (which I think it's the default connection method in arclight). If you could shed any insights on solution to this problem, or better way than I proposed above, please let me know. I would be more than happy to try it out and really appreciated it!

**Comment by seanaery** [comment]
Hi @andyzyl321 --

This gets a bit complicated. I'm not sure what the best approach might be, so take these ideas with a grain of salt.

If it's important to distinguish between the different kinds of extent values and pull them together in a custom way for display in one field, I'd look at setting something up like what is present for `normalized_date_ssm`. I.e., use xpath to capture the different extent types in different/new Solr fields (e.g., `extent_materialtype_ssm` vs. `extent_carrier_ssm`), then create a class, called something like `NormalizedExtent`, that can assemble those pieces together in whatever way you need.

Another idea: given that the out-of-the-box `ead2_config.rb` setup is going to ignore/discard the altrender attributes for extent, you could add to the `extract_xpath` part:
`to_text: false`

That'll retain the raw XML for any extent field values, but then you'd need to develop custom display logic around it to turn it into the desired HTML in the view. You could look at the existing `render_html_tags` helper method as an example and maybe create a `render_extent` helper method. Note you can apply helper methods for rendering field values in their configuration in your `catalog_controller.rb`, e.g.:
`config.add_component_field 'extent_ssm', label: 'Extent', helper_method: :render_extent`

**Comment by dinahhandel** [comment]
Worth discussion, assessing what current implementers have done to get around the issue.

**Comment by marlo-longley** [comment]
Closed by #1446
